export const API_ROUTES = Object.freeze({
  ADMIN_DASHBOARD: '/api/admin/dashboard',
  ADMIN_API_KEYS: '/api/admin/api-keys',
  ADMIN_PROVIDER_IDENTITY: '/api/admin/provider-identities/:login',
  AGENT_CALLBACK_JOBS: '/api/agent-callbacks/jobs',
  AGENT_SELECTION_INDEX: '/api/agent-selection-index',
  AGENTS: '/api/agents',
  AGENTS_DRAFT_SKILL_MANIFEST: '/api/agents/draft-skill-manifest',
  AGENTS_IMPORT_MANIFEST: '/api/agents/import-manifest',
  AGENTS_IMPORT_URL: '/api/agents/import-url',
  ANALYTICS_CHAT_TRANSCRIPTS: '/api/analytics/chat-transcripts',
  ANALYTICS_EVENTS: '/api/analytics/events',
  APP_CONTEXTS: '/api/app-contexts',
  APP_CONTEXT_DETAIL: '/api/app-contexts/:context_id',
  APPS: '/api/apps',
  APPS_IMPORT_MANIFEST: '/api/apps/import-manifest',
  APPS_IMPORT_URL: '/api/apps/import-url',
  BILLING_AUDITS: '/api/billing-audits',
  CHAT_MEMORY: '/api/chat-memory',
  CHAT_SESSIONS: '/api/chat-sessions',
  CONNECTORS_GOOGLE_ANALYTICS_REPORT: '/api/connectors/google/analytics-report',
  CONNECTORS_GOOGLE_ASSETS: '/api/connectors/google/assets',
  CONNECTORS_GOOGLE_SEND_GMAIL: '/api/connectors/google/send-gmail',
  CONNECTORS_INSTAGRAM_POST: '/api/connectors/instagram/post',
  CONNECTORS_RESEND_SEND_EMAIL: '/api/connectors/resend/send-email',
  CONNECTORS_WORDPRESS_CONNECT: '/api/connectors/wordpress/connect',
  CONNECTORS_WORDPRESS_CREATE_DRAFT: '/api/connectors/wordpress/create-draft',
  CONNECTORS_WORDPRESS_STATUS: '/api/connectors/wordpress/status',
  CONNECTORS_X_POST: '/api/connectors/x/post',
  CONNECTORS_X_STATUS: '/api/connectors/x/status',
  DELIVERIES_CLASSIFY: '/api/deliveries/classify',
  DELIVERIES_EXECUTE: '/api/deliveries/execute',
  DELIVERIES_PREPARE_EXECUTION: '/api/deliveries/prepare-execution',
  DELIVERIES_PREPARE_PUBLISH: '/api/deliveries/prepare-publish',
  DELIVERIES_PREPARE_PUBLISH_ORDER: '/api/deliveries/prepare-publish-order',
  DELIVERIES_SCHEDULE: '/api/deliveries/schedule',
  DELIVERY_ITEMS: '/api/delivery-items',
  DEV_DISPATCH_RETRY: '/api/dev/dispatch-retry',
  DEV_RECURRING_SWEEP: '/api/dev/recurring-sweep',
  DEV_RESOLVE_JOB: '/api/dev/resolve-job',
  DEV_TIMEOUT_SWEEP: '/api/dev/timeout-sweep',
  FEEDBACK: '/api/feedback',
  GITHUB_APP_SETUP: '/api/github/app-setup',
  GITHUB_CREATE_ADAPTER_PR: '/api/github/create-adapter-pr',
  GITHUB_CREATE_EXECUTOR_PR: '/api/github/create-executor-pr',
  GITHUB_GENERATE_MANIFEST: '/api/github/generate-manifest',
  GITHUB_IMPORT_REPO: '/api/github/import-repo',
  GITHUB_LOAD_MANIFEST: '/api/github/load-manifest',
  GITHUB_REPOS: '/api/github/repos',
  GUEST_TRIAL_CLAIM: '/api/guest-trial/claim',
  HEALTH: '/api/health',
  INTERNAL_CRON_WORKFLOW_COMPLETIONS: '/api/internal/cron/workflow-completions',
  INTERNAL_TEST_WELCOME_EMAIL: '/api/internal/test-welcome-email',
  JOBS: '/api/jobs',
  JOBS_PREFIX: '/api/jobs/',
  METRICS: '/api/metrics',
  OPEN_CHAT_INTENT: '/api/open-chat/intent',
  PRICING_CATALOG: '/api/pricing-catalog',
  READY: '/api/ready',
  RECURRING_ORDERS: '/api/recurring-orders',
  SCHEMA: '/api/schema',
  SEED: '/api/seed',
  SETTINGS: '/api/settings',
  SETTINGS_API_KEYS: '/api/settings/api-keys',
  SETTINGS_APP_SETTINGS: '/api/settings/app-settings',
  SETTINGS_BILLING: '/api/settings/billing',
  SETTINGS_CHAT_TRAINING_DATA: '/api/settings/chat-training-data',
  SETTINGS_EXACT_ACTIONS: '/api/settings/exact-actions',
  SETTINGS_EXECUTOR_PREFERENCES: '/api/settings/executor-preferences',
  SETTINGS_FEEDBACK_REPORTS: '/api/settings/feedback-reports',
  SETTINGS_PAYOUT: '/api/settings/payout',
  SETTINGS_PROVIDER_IDENTITY: '/api/settings/provider-identity',
  SNAPSHOT: '/api/snapshot',
  STATS: '/api/stats',
  STRIPE_CONNECT_ONBOARDING: '/api/stripe/connect/onboarding',
  STRIPE_MONTHLY_CHARGE_RUN: '/api/stripe/monthly-charge/run',
  STRIPE_PAYOUT_RUN: '/api/stripe/payout/run',
  STRIPE_PROVIDER_MONTHLY_CHARGE_RUN: '/api/stripe/provider-monthly-charge/run',
  STRIPE_SETUP_SESSION: '/api/stripe/setup-session',
  STRIPE_STATUS: '/api/stripe/status',
  STRIPE_SUBSCRIPTION_SESSION: '/api/stripe/subscription-session',
  STRIPE_WEBHOOK: '/api/stripe/webhook',
  VERSION: '/api/version',
  WORK_PREFLIGHT_ORDER: '/api/work/preflight-order',
  WORK_PREPARE_ORDER: '/api/work/prepare-order',
  WORK_RESOLVE_ACTION: '/api/work/resolve-action',
  WORK_RESOLVE_INTENT: '/api/work/resolve-intent'
});

const BOTH_RUNTIMES = Object.freeze(['worker', 'server']);
const WORKER_ONLY = Object.freeze(['worker']);
const ANY_METHOD = Object.freeze([]);

export const API_ROUTE_METHODS = Object.freeze({
  ADMIN_DASHBOARD: ['GET'],
  ADMIN_API_KEYS: ['POST'],
  ADMIN_PROVIDER_IDENTITY: ['GET', 'POST'],
  AGENT_CALLBACK_JOBS: ['POST'],
  AGENT_SELECTION_INDEX: ['GET'],
  AGENTS: ['GET', 'POST'],
  AGENTS_DRAFT_SKILL_MANIFEST: ['POST'],
  AGENTS_IMPORT_MANIFEST: ['POST'],
  AGENTS_IMPORT_URL: ['POST'],
  ANALYTICS_CHAT_TRANSCRIPTS: ['POST'],
  ANALYTICS_EVENTS: ['POST'],
  APP_CONTEXTS: ['GET', 'POST'],
  APP_CONTEXT_DETAIL: ['GET'],
  APPS: ['GET', 'POST'],
  APPS_IMPORT_MANIFEST: ['POST'],
  APPS_IMPORT_URL: ['POST'],
  BILLING_AUDITS: ['GET'],
  CHAT_MEMORY: ['GET'],
  CHAT_SESSIONS: ['POST'],
  CONNECTORS_GOOGLE_ANALYTICS_REPORT: ['GET'],
  CONNECTORS_GOOGLE_ASSETS: ['GET'],
  CONNECTORS_GOOGLE_SEND_GMAIL: ['POST'],
  CONNECTORS_INSTAGRAM_POST: ['POST'],
  CONNECTORS_RESEND_SEND_EMAIL: ['POST'],
  CONNECTORS_WORDPRESS_CONNECT: ['POST'],
  CONNECTORS_WORDPRESS_CREATE_DRAFT: ['POST'],
  CONNECTORS_WORDPRESS_STATUS: ['GET'],
  CONNECTORS_X_POST: ['POST'],
  CONNECTORS_X_STATUS: ['GET'],
  DELIVERIES_CLASSIFY: ['POST'],
  DELIVERIES_EXECUTE: ['POST'],
  DELIVERIES_PREPARE_EXECUTION: ['POST'],
  DELIVERIES_PREPARE_PUBLISH: ['POST'],
  DELIVERIES_PREPARE_PUBLISH_ORDER: ['POST'],
  DELIVERIES_SCHEDULE: ['POST'],
  DELIVERY_ITEMS: ['GET'],
  DEV_DISPATCH_RETRY: ['POST'],
  DEV_RECURRING_SWEEP: ['POST'],
  DEV_RESOLVE_JOB: ['POST'],
  DEV_TIMEOUT_SWEEP: ['POST'],
  FEEDBACK: ['POST'],
  GITHUB_APP_SETUP: ['GET'],
  GITHUB_CREATE_ADAPTER_PR: ['POST'],
  GITHUB_CREATE_EXECUTOR_PR: ['POST'],
  GITHUB_GENERATE_MANIFEST: ['POST'],
  GITHUB_IMPORT_REPO: ['POST'],
  GITHUB_LOAD_MANIFEST: ['POST'],
  GITHUB_REPOS: ['GET'],
  GUEST_TRIAL_CLAIM: ['POST'],
  HEALTH: ['GET'],
  INTERNAL_CRON_WORKFLOW_COMPLETIONS: ['POST'],
  INTERNAL_TEST_WELCOME_EMAIL: ['POST'],
  JOBS: ['GET', 'POST'],
  JOBS_PREFIX: ANY_METHOD,
  METRICS: ['GET'],
  OPEN_CHAT_INTENT: ['POST'],
  PRICING_CATALOG: ['GET'],
  READY: ['GET'],
  RECURRING_ORDERS: ['GET', 'POST'],
  SCHEMA: ['GET'],
  SEED: ['POST'],
  SETTINGS: ['GET'],
  SETTINGS_API_KEYS: ['GET', 'POST'],
  SETTINGS_APP_SETTINGS: ['GET', 'POST'],
  SETTINGS_BILLING: ['POST'],
  SETTINGS_CHAT_TRAINING_DATA: ['GET'],
  SETTINGS_EXACT_ACTIONS: ['GET', 'POST'],
  SETTINGS_EXECUTOR_PREFERENCES: ['POST'],
  SETTINGS_FEEDBACK_REPORTS: ['GET'],
  SETTINGS_PAYOUT: ['POST'],
  SETTINGS_PROVIDER_IDENTITY: ['POST'],
  SNAPSHOT: ['GET'],
  STATS: ['GET'],
  STRIPE_CONNECT_ONBOARDING: ['POST'],
  STRIPE_MONTHLY_CHARGE_RUN: ['POST'],
  STRIPE_PAYOUT_RUN: ['POST'],
  STRIPE_PROVIDER_MONTHLY_CHARGE_RUN: ['POST'],
  STRIPE_SETUP_SESSION: ['POST'],
  STRIPE_STATUS: ['GET'],
  STRIPE_SUBSCRIPTION_SESSION: ['POST'],
  STRIPE_WEBHOOK: ['POST'],
  VERSION: ['GET'],
  WORK_PREFLIGHT_ORDER: ['POST'],
  WORK_PREPARE_ORDER: ['POST'],
  WORK_RESOLVE_ACTION: ['POST'],
  WORK_RESOLVE_INTENT: ['POST']
});

export const API_ROUTE_MANIFEST = Object.freeze([
  ['ADMIN_DASHBOARD', BOTH_RUNTIMES],
  ['ADMIN_API_KEYS', BOTH_RUNTIMES],
  ['ADMIN_PROVIDER_IDENTITY', BOTH_RUNTIMES],
  ['AGENT_CALLBACK_JOBS', BOTH_RUNTIMES],
  ['AGENT_SELECTION_INDEX', BOTH_RUNTIMES],
  ['AGENTS', BOTH_RUNTIMES],
  ['AGENTS_DRAFT_SKILL_MANIFEST', BOTH_RUNTIMES],
  ['AGENTS_IMPORT_MANIFEST', BOTH_RUNTIMES],
  ['AGENTS_IMPORT_URL', BOTH_RUNTIMES],
  ['ANALYTICS_CHAT_TRANSCRIPTS', BOTH_RUNTIMES],
  ['ANALYTICS_EVENTS', BOTH_RUNTIMES],
  ['APP_CONTEXTS', BOTH_RUNTIMES],
  ['APP_CONTEXT_DETAIL', BOTH_RUNTIMES],
  ['APPS', BOTH_RUNTIMES],
  ['APPS_IMPORT_MANIFEST', BOTH_RUNTIMES],
  ['APPS_IMPORT_URL', BOTH_RUNTIMES],
  ['BILLING_AUDITS', BOTH_RUNTIMES],
  ['CHAT_MEMORY', BOTH_RUNTIMES],
  ['CHAT_SESSIONS', BOTH_RUNTIMES],
  ['CONNECTORS_GOOGLE_ANALYTICS_REPORT', BOTH_RUNTIMES],
  ['CONNECTORS_GOOGLE_ASSETS', BOTH_RUNTIMES],
  ['CONNECTORS_GOOGLE_SEND_GMAIL', BOTH_RUNTIMES],
  ['CONNECTORS_INSTAGRAM_POST', BOTH_RUNTIMES],
  ['CONNECTORS_RESEND_SEND_EMAIL', BOTH_RUNTIMES],
  ['CONNECTORS_WORDPRESS_CONNECT', BOTH_RUNTIMES],
  ['CONNECTORS_WORDPRESS_CREATE_DRAFT', BOTH_RUNTIMES],
  ['CONNECTORS_WORDPRESS_STATUS', BOTH_RUNTIMES],
  ['CONNECTORS_X_POST', BOTH_RUNTIMES],
  ['CONNECTORS_X_STATUS', BOTH_RUNTIMES],
  ['DELIVERIES_CLASSIFY', BOTH_RUNTIMES],
  ['DELIVERIES_EXECUTE', BOTH_RUNTIMES],
  ['DELIVERIES_PREPARE_EXECUTION', BOTH_RUNTIMES],
  ['DELIVERIES_PREPARE_PUBLISH', BOTH_RUNTIMES],
  ['DELIVERIES_PREPARE_PUBLISH_ORDER', BOTH_RUNTIMES],
  ['DELIVERIES_SCHEDULE', BOTH_RUNTIMES],
  ['DELIVERY_ITEMS', BOTH_RUNTIMES],
  ['DEV_DISPATCH_RETRY', BOTH_RUNTIMES],
  ['DEV_RECURRING_SWEEP', BOTH_RUNTIMES],
  ['DEV_RESOLVE_JOB', BOTH_RUNTIMES],
  ['DEV_TIMEOUT_SWEEP', BOTH_RUNTIMES],
  ['FEEDBACK', BOTH_RUNTIMES],
  ['GITHUB_APP_SETUP', BOTH_RUNTIMES],
  ['GITHUB_CREATE_ADAPTER_PR', BOTH_RUNTIMES],
  ['GITHUB_CREATE_EXECUTOR_PR', BOTH_RUNTIMES],
  ['GITHUB_GENERATE_MANIFEST', BOTH_RUNTIMES],
  ['GITHUB_IMPORT_REPO', BOTH_RUNTIMES],
  ['GITHUB_LOAD_MANIFEST', BOTH_RUNTIMES],
  ['GITHUB_REPOS', BOTH_RUNTIMES],
  ['GUEST_TRIAL_CLAIM', BOTH_RUNTIMES],
  ['HEALTH', BOTH_RUNTIMES],
  ['INTERNAL_CRON_WORKFLOW_COMPLETIONS', WORKER_ONLY],
  ['INTERNAL_TEST_WELCOME_EMAIL', WORKER_ONLY],
  ['JOBS', BOTH_RUNTIMES],
  ['JOBS_PREFIX', BOTH_RUNTIMES],
  ['METRICS', BOTH_RUNTIMES],
  ['OPEN_CHAT_INTENT', BOTH_RUNTIMES],
  ['PRICING_CATALOG', BOTH_RUNTIMES],
  ['READY', BOTH_RUNTIMES],
  ['RECURRING_ORDERS', BOTH_RUNTIMES],
  ['SCHEMA', BOTH_RUNTIMES],
  ['SEED', BOTH_RUNTIMES],
  ['SETTINGS', BOTH_RUNTIMES],
  ['SETTINGS_API_KEYS', BOTH_RUNTIMES],
  ['SETTINGS_APP_SETTINGS', BOTH_RUNTIMES],
  ['SETTINGS_BILLING', BOTH_RUNTIMES],
  ['SETTINGS_CHAT_TRAINING_DATA', BOTH_RUNTIMES],
  ['SETTINGS_EXACT_ACTIONS', BOTH_RUNTIMES],
  ['SETTINGS_EXECUTOR_PREFERENCES', BOTH_RUNTIMES],
  ['SETTINGS_FEEDBACK_REPORTS', BOTH_RUNTIMES],
  ['SETTINGS_PAYOUT', BOTH_RUNTIMES],
  ['SETTINGS_PROVIDER_IDENTITY', BOTH_RUNTIMES],
  ['SNAPSHOT', BOTH_RUNTIMES],
  ['STATS', BOTH_RUNTIMES],
  ['STRIPE_CONNECT_ONBOARDING', BOTH_RUNTIMES],
  ['STRIPE_MONTHLY_CHARGE_RUN', BOTH_RUNTIMES],
  ['STRIPE_PAYOUT_RUN', BOTH_RUNTIMES],
  ['STRIPE_PROVIDER_MONTHLY_CHARGE_RUN', BOTH_RUNTIMES],
  ['STRIPE_SETUP_SESSION', BOTH_RUNTIMES],
  ['STRIPE_STATUS', BOTH_RUNTIMES],
  ['STRIPE_SUBSCRIPTION_SESSION', BOTH_RUNTIMES],
  ['STRIPE_WEBHOOK', BOTH_RUNTIMES],
  ['VERSION', BOTH_RUNTIMES],
  ['WORK_PREFLIGHT_ORDER', BOTH_RUNTIMES],
  ['WORK_PREPARE_ORDER', BOTH_RUNTIMES],
  ['WORK_RESOLVE_ACTION', BOTH_RUNTIMES],
  ['WORK_RESOLVE_INTENT', BOTH_RUNTIMES]
].map(([key, runtimes]) => Object.freeze({
  key,
  path: API_ROUTES[key],
  methods: Object.freeze([...(API_ROUTE_METHODS[key] || ANY_METHOD)]),
  runtimes
})));

export const API_ROUTE_BY_KEY = Object.freeze(Object.fromEntries(API_ROUTE_MANIFEST.map((route) => [route.key, route])));

export function apiRouteManifestForRuntime(runtime = '') {
  const target = String(runtime || '').trim();
  return API_ROUTE_MANIFEST.filter((route) => route.runtimes.includes(target));
}

function escapeRoutePatternPart(value = '') {
  return String(value || '').replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function apiRoutePathMatches(pathname = '', routePath = '') {
  const path = String(pathname || '');
  const template = String(routePath || '');
  if (!path || !template) return false;
  if (path === template) return true;
  if (!template.includes(':')) return false;
  const pattern = template
    .split('/')
    .map((part) => part.startsWith(':') ? '[^/]+' : escapeRoutePatternPart(part))
    .join('/');
  return new RegExp(`^${pattern}$`).test(path);
}

export function apiRouteMatches(pathname = '', method = '', routeKey = '', expectedMethod = '') {
  const route = API_ROUTE_BY_KEY[String(routeKey || '').trim()] || null;
  if (!route || !apiRoutePathMatches(pathname, route.path)) return false;
  const normalizedMethod = String(method || '').trim().toUpperCase();
  const allowedMethods = expectedMethod
    ? [String(expectedMethod || '').trim().toUpperCase()].filter(Boolean)
    : route.methods;
  return !allowedMethods.length || allowedMethods.includes(normalizedMethod);
}
