import {
  buildDeliveryPublishOrderBody,
  buildReportNextOrderBody,
  deliveryExecutionConfirmationRequirement,
  deliveryExecutorActionPayload,
  deliveryScheduleConfirmationRequirement,
  hasDeliveryExecutionConfirmation,
  hasDeliveryScheduleConfirmation,
  isDeliveryExecutionActionSupported,
  isDeliveryScheduleActionSupported,
  normalizeDeliveryExecuteResponse,
  normalizeDeliveryScheduleResponse,
  prepareDeliveryExecutionResponsePayload,
  prepareDeliveryPublishResponsePayload
} from '../../public/delivery-action-contract.js';

const GITHUB_EXECUTOR_MARKER = 'Generated by AIagent2 executor';
const PRODUCT_SHORT_NAME = 'CAIt';

function normalizeGithubExecutorPath(value = '') {
  const normalized = String(value || '').trim().replace(/\\/g, '/').replace(/^\/+/, '').replace(/\/{2,}/g, '/');
  if (!normalized || normalized.endsWith('/')) return '';
  if (normalized.includes('..') || normalized.startsWith('.')) return '';
  return normalized.slice(0, 180);
}

function sanitizeGithubExecutorSlug(value = '', fallback = 'delivery') {
  const slug = String(value || '')
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
  return (slug || fallback).slice(0, 48);
}

function githubExecutorPlanFromRequest(body = {}, repoMeta = {}) {
  const kind = sanitizeGithubExecutorSlug(body.kind || body.executor_kind || 'delivery');
  const rawTitle = String(body.title || body.source_delivery_title || kind).trim();
  const sourceJobId = String(body.source_job_id || body.job_id || body.jobId || '').trim();
  const titleSlug = sanitizeGithubExecutorSlug(rawTitle, kind);
  const shortJobId = sanitizeGithubExecutorSlug(sourceJobId, 'job').slice(0, 12);
  const branchName = `cait/${sanitizeGithubExecutorSlug(kind, 'executor')}-${titleSlug}-${shortJobId}`.slice(0, 120);
  const requestedPath = normalizeGithubExecutorPath(body.repo_path || '');
  const fallbackName = `${titleSlug || kind}-${shortJobId || 'delivery'}.md`;
  const filePath = requestedPath || `cait-deliveries/${fallbackName}`;
  const content = String(body.content || '').trim();
  const fileContent = [
    `${GITHUB_EXECUTOR_MARKER}`,
    `Generated by ${PRODUCT_SHORT_NAME} executor for \`${repoMeta.full_name || `${body.owner}/${body.repo}`}\`.`,
    '',
    content
  ].join('\n');
  const prTitle = String(body.pr_title || body.prTitle || `Add ${PRODUCT_SHORT_NAME} ${kind} handoff: ${rawTitle || kind}`).trim().slice(0, 180);
  const prBody = [
    `This PR was prepared from a ${PRODUCT_SHORT_NAME} delivery action.`,
    '',
    `- Source job: ${sourceJobId || 'not provided'}`,
    `- Executor kind: ${kind}`,
    `- File: \`${filePath}\``,
    '',
    'Review the generated file before merging.'
  ].join('\n');
  return { kind, branchName, filePath, fileContent, prTitle, prBody };
}

export function createDeliveryRouteHandlers(deps = {}) {
  const {
    accountSettingsForLogin,
    canViewJobFromRequest,
    createGithubBranch,
    createGithubPullRequest,
    createRecurringOrderInState,
    currentAgentRequesterContext,
    currentOrderRequesterContext,
    executeScheduledExactConnectorAction,
    fetchGithubBranchSha,
    fetchGithubRepoMeta,
    fetchGithubTextFile,
    GITHUB_ADAPTER_MARKER,
    githubAppRepoTokenForRequester,
    githubPermissionError,
    handleCreateWorkflowJob,
    hasRepoWriteConfirmation,
    normalizeOrderStrategy,
    parseBody,
    performSingleJobCreate,
    prepareGuestTrialOrderContext,
    promptInjectionGuardForPrompt,
    promptPolicyBlockPayload,
    recordOrderApiKeyUsage,
    requireOrderWriteAccess,
    resolveOrderStrategy,
    sessionHasGithubApp,
    touchEvent,
    upsertGithubTextFile
  } = deps;

  async function prepareDeliveryExecutionRequest(storage, request, env) {
    const body = await parseBody(request).catch((error) => ({ __error: error.message }));
    if (body.__error) return { error: body.__error, statusCode: 400 };
    const type = String(body.content_type || body.contentType || '').trim();
    if (!type) return { error: 'content_type required', statusCode: 400 };
    const current = await currentOrderRequesterContext(storage, request, env);
    if (!current.user && current.apiKeyStatus === 'invalid') return { error: 'Invalid API key', statusCode: 401 };
    if (!current.user && current.apiKeyStatus !== 'valid') return { error: 'Login or CAIt API key required', statusCode: 401 };
    const jobId = String(body.job_id || body.jobId || '').trim();
    const state = jobId || current?.login ? await storage.getState() : { jobs: [], accounts: [] };
    if (jobId) {
      const job = Array.isArray(state.jobs) ? state.jobs.find((item) => String(item?.id || '') === jobId) : null;
      if (!job || !canViewJobFromRequest(state, current, env, job, request)) {
        return { error: 'Job not found or access denied', statusCode: 404 };
      }
    }
    const account = current?.login ? accountSettingsForLogin(state, current.login, current.user, current.authProvider) : null;
    const connectors = account?.connectors || {};
    const executorPreferences = account?.executorPreferences || {};
    return prepareDeliveryExecutionResponsePayload(type, body, {
      current,
      connectors,
      executorPreferences
    });
  }

  async function prepareDeliveryPublishRequest(storage, request, env) {
    const body = await parseBody(request).catch((error) => ({ __error: error.message }));
    if (body.__error) return { error: body.__error, statusCode: 400 };
    const current = await currentOrderRequesterContext(storage, request, env);
    if (!current.user && current.apiKeyStatus === 'invalid') return { error: 'Invalid API key', statusCode: 401 };
    if (!current.user && current.apiKeyStatus !== 'valid') return { error: 'Login or CAIt API key required', statusCode: 401 };
    const jobId = String(body.job_id || body.jobId || '').trim();
    const state = jobId || current?.login ? await storage.getState() : { jobs: [], accounts: [] };
    if (jobId) {
      const job = Array.isArray(state.jobs) ? state.jobs.find((item) => String(item?.id || '') === jobId) : null;
      if (!job || !canViewJobFromRequest(state, current, env, job, request)) {
        return { error: 'Job not found or access denied', statusCode: 404 };
      }
    }
    const account = current?.login ? accountSettingsForLogin(state, current.login, current.user, current.authProvider) : null;
    const connectors = account?.connectors || {};
    const githubReady = Boolean(current?.githubLinked || connectors?.github?.connected);
    return prepareDeliveryPublishResponsePayload(body, { githubReady });
  }

  async function prepareDeliveryPublishOrderRequest(storage, request, env) {
    const body = await parseBody(request).catch((error) => ({ __error: error.message }));
    if (body.__error) return { error: body.__error, statusCode: 400 };
    const current = await currentOrderRequesterContext(storage, request, env);
    if (!current.user && current.apiKeyStatus === 'invalid') return { error: 'Invalid API key', statusCode: 401 };
    if (!current.user && current.apiKeyStatus !== 'valid') return { error: 'Login or CAIt API key required', statusCode: 401 };
    const jobId = String(body.job_id || body.jobId || '').trim();
    if (!jobId) return { error: 'job_id required', statusCode: 400 };
    const state = await storage.getState();
    const job = Array.isArray(state.jobs) ? state.jobs.find((item) => String(item?.id || '') === jobId) : null;
    if (!job || !canViewJobFromRequest(state, current, env, job, request)) {
      return { error: 'Job not found or access denied', statusCode: 404 };
    }
    const articleTitle = String(body.title || '').trim();
    const articleContent = String(body.content || '').trim();
    if (!articleContent) return { error: 'content required', statusCode: 400 };
    return buildDeliveryPublishOrderBody(job, { ...body, title: articleTitle });
  }

  function deliveryFollowupTaskForChannel(channel = '', fallback = 'research') {
    const normalized = String(channel || '').trim();
    if (normalized === 'x') return 'x_post';
    if (normalized === 'instagram') return 'instagram';
    if (normalized === 'reddit') return 'reddit';
    if (normalized === 'indie_hackers') return 'indie_hackers';
    if (normalized === 'email') return 'email_ops';
    if (normalized === 'github') return 'code';
    return String(fallback || 'research').trim() || 'research';
  }

  function buildGenericDeliveryFollowupOrderBody(job = null, body = {}) {
    const deliverable = body?.deliverable && typeof body.deliverable === 'object' ? body.deliverable : {};
    const draft = body?.draft && typeof body.draft === 'object' ? body.draft : {};
    const type = String(deliverable.type || body.content_type || body.contentType || '').trim();
    const title = String(deliverable.title || body.title || 'Delivery').trim();
    let taskType = String(job?.taskType || 'research').trim() || 'research';
    let orderStrategy = 'single';
    let promptLines = [];
    const directFollowup = body.direct === true || body.direct_followup === true || body.mode === 'direct';
    if (directFollowup) {
      const agentId = String(job?.assignedAgentId || '').trim();
      const answer = String(body.answer || body.followup_answer || body.followupAnswer || '').trim();
      promptLines = [
        `Direct follow-up for previous order ${job?.id || ''}:`,
        '',
        answer || 'Please refine the previous delivery. Ask only if a missing detail blocks the revision.',
        '',
        'Use input._broker.conversation.previousJob as the prior delivery context. Continue with the same agent and improve the delivered output instead of starting a new CAIt intake.'
      ];
      return {
        ok: true,
        parent_agent_id: job?.parentAgentId || 'cloudcode-main',
        followup_to_job_id: String(job?.id || ''),
        task_type: taskType,
        agent_id: agentId,
        order_strategy: 'single',
        prompt: promptLines.filter(Boolean).join('\n'),
        skip_intake: true,
        input: {
          _broker: {
            directFollowup: {
              sourceJobId: String(job?.id || ''),
              sourceAgentId: agentId,
              createdAt: new Date().toISOString()
            }
          }
        }
      };
    }
    if (type === 'social_post_pack') {
      const channel = String(draft.channel || 'x').trim();
      const actionMode = String(draft.actionMode || 'draft_only').trim();
      taskType = deliveryFollowupTaskForChannel(channel, 'marketing');
      promptLines = [
        `Use the social post pack from previous order ${job?.id || ''}.`,
        '',
        `Detected delivery: ${title}`,
        `Channel: ${channel}`,
        `Mode: ${actionMode}`,
        'Turn this into an execution-ready social publishing order.',
        'Adapt the copy for the selected channel, keep the strongest hooks, and ask only for the minimum missing posting detail.',
        actionMode === 'post_ready'
          ? 'If direct posting authority exists, prepare the publish path. Otherwise return the final post pack and the exact next action.'
          : actionMode === 'schedule_ready'
            ? 'If scheduling authority exists, prepare the exact scheduled publish path. Otherwise return the final post pack and the minimum missing scheduling detail.'
            : 'Return the final reviewed post pack and the exact publish step the user should approve next.'
      ];
    } else if (type === 'email_pack') {
      const actionMode = String(draft.actionMode || 'draft_only').trim();
      taskType = 'email_ops';
      promptLines = [
        `Use the email pack from previous order ${job?.id || ''}.`,
        '',
        `Detected delivery: ${title}`,
        `Mode: ${actionMode}`,
        String(draft.recipientEmail || '').trim() ? `Recipient: ${String(draft.recipientEmail || '').trim()}` : '',
        String(draft.emailSubject || '').trim() ? `Subject: ${String(draft.emailSubject || '').trim()}` : '',
        'Turn this into an execution-ready email order.',
        actionMode === 'send_ready'
          ? 'If Gmail send authority exists, prepare the exact send path. Otherwise return the final draft and the exact next approval action.'
          : actionMode === 'schedule_ready'
            ? 'If scheduling authority exists, prepare the exact scheduled send path. Otherwise return the final draft and the exact next approval action.'
            : 'Return the final reviewed draft and the exact send step the user should approve next.'
      ];
    } else if (type === 'code_handoff') {
      const target = String(draft.target || 'github_repo').trim();
      const executionMode = String(draft.executionMode || 'draft_pr').trim();
      const repoFullName = String(draft.repoFullName || '').trim();
      taskType = 'code';
      promptLines = [
        `Implement the technical handoff from previous order ${job?.id || ''}.`,
        '',
        `Detected delivery: ${title}`,
        `Execution target: ${target}`,
        `Mode: ${executionMode}`,
        repoFullName ? `Repository: ${repoFullName}` : '',
        'Use the previous delivery as the implementation brief.',
        target === 'github_repo'
          ? 'Prefer GitHub-connected execution. Create a draft PR or implementation-ready branch plan without restarting discovery.'
          : target === 'local_terminal'
            ? 'Prepare a local terminal handoff with the minimum safe command plan and exact file targets.'
            : 'Return an exportable implementation bundle and the next action needed to apply it safely.',
        'Ask only for the missing repository or runtime detail if required.'
      ];
    } else if (deliverable.content) {
      const nextStep = String(draft.nextStep || 'action_plan').trim();
      const executionChannel = String(draft.channel || '').trim();
      taskType = nextStep === 'publish_followup'
        ? 'writing'
        : (nextStep === 'execution_order' ? deliveryFollowupTaskForChannel(executionChannel, job?.taskType || 'research') : 'research');
      orderStrategy = type === 'report_bundle' && nextStep !== 'execution_order' ? 'auto' : 'single';
      const sourceLines = [];
      if (String(draft.googleSearchConsoleSite || '').trim()) sourceLines.push(`Use Search Console site: ${String(draft.googleSearchConsoleSite || '').trim()}`);
      if (String(draft.googleGa4Property || '').trim()) sourceLines.push(`Use GA4 property: ${String(draft.googleGa4Property || '').trim()}`);
      if (String(draft.googleDriveFileId || '').trim()) sourceLines.push(`Use Google Drive file: ${String(draft.googleDriveFileId || '').trim()}`);
      if (String(draft.googleCalendarId || '').trim()) sourceLines.push(`Use Google Calendar: ${String(draft.googleCalendarId || '').trim()}`);
      if (String(draft.googleGmailLabelId || '').trim()) sourceLines.push(`Use Gmail label: ${String(draft.googleGmailLabelId || '').trim()}`);
      if (executionChannel) sourceLines.push(`Execution channel selected by user: ${executionChannel}`);
      promptLines = [
        `Continue from the report delivered in previous order ${job?.id || ''}.`,
        '',
        `Detected delivery: ${title}`,
        `Next step: ${nextStep}`,
        ...sourceLines,
        nextStep === 'publish_followup'
          ? 'Convert the report into a publishable follow-up order and ask only for the minimum publishing metadata.'
          : nextStep === 'execution_order'
            ? 'Convert the report into the next executable work order directly.'
            : 'Turn the report into a concise action plan with the next best recommended step.',
        'If another clarification is required, ask only one blocking question.'
      ];
    } else {
      const answer = String(body.answer || body.followup_answer || body.followupAnswer || '').trim();
      taskType = String(job?.taskType || 'research').trim() || 'research';
      orderStrategy = 'single';
      promptLines = [
        `Follow-up for previous order ${job?.id || ''}:`,
        '',
        answer || 'Continue from the previous delivery. Use the prior context and ask only the remaining important questions if needed.',
        '',
        'Use the previous order context, fold in this new answer, and produce the next best delivery.'
      ];
    }
    return {
      ok: true,
      followup_to_job_id: String(job?.id || ''),
      task_type: taskType,
      order_strategy: orderStrategy,
      prompt: promptLines.filter(Boolean).join('\n')
    };
  }

  function buildRunningOrderFollowupOrderBody(job = null, body = {}) {
    const workflow = job?.workflow && typeof job.workflow === 'object'
      ? job.workflow
      : (job?.input?._broker?.workflow && typeof job.input._broker.workflow === 'object' ? job.input._broker.workflow : {});
    const plannedTasks = Array.isArray(workflow?.plannedTasks)
      ? workflow.plannedTasks.map((item) => String(item || '').trim()).filter(Boolean)
      : [];
    const taskType = String(plannedTasks[0] || job?.taskType || 'research').trim().toLowerCase() || 'research';
    const orderStrategy = job?.jobKind === 'workflow' || job?.workflow ? 'multi' : 'single';
    const answer = String(body.answer || body.followup_answer || body.followupAnswer || '').trim();
    const requestedAt = new Date().toISOString();
    const promptLines = [
      `Follow-up/change request for running order ${job?.id || ''}:`,
      answer,
      '',
      'Use the previous order context, completed specialist outputs, active blockers, and current workflow state. Treat this as an additive/revised instruction, not a separate unrelated request.'
    ];
    const conversationOwner = taskType.endsWith('_leader')
      ? { type: 'leader', taskType, label: String(job?.workflowAgentName || job?.agentName || taskType).trim(), reason: 'Follow-up request for active leader workflow.' }
      : { type: 'cait', label: PRODUCT_SHORT_NAME, reason: 'Follow-up request for active order.' };
    return {
      ok: true,
      followup_to_job_id: String(job?.id || ''),
      task_type: taskType,
      order_strategy: orderStrategy,
      prompt: promptLines.filter(Boolean).join('\n'),
      reason: `Prepared as an add-on request for running order ${String(job?.id || '').slice(0, 8)}. It will not run until Send order is pressed.`,
      conversation_owner: conversationOwner,
      skip_intake: true,
      input: {
        _broker: {
          conversation: {
            mode: 'followup',
            userExplicitContinuation: true,
            explicitContinuation: true,
            followupToJobId: String(job?.id || ''),
            followup_to_job_id: String(job?.id || ''),
            requestedAt
          }
        }
      }
    };
  }

  async function prepareDeliveryFollowupOrderRequest(storage, request, env) {
    const body = await parseBody(request).catch((error) => ({ __error: error.message }));
    if (body.__error) return { error: body.__error, statusCode: 400 };
    const current = await currentOrderRequesterContext(storage, request, env);
    if (!current.user && current.apiKeyStatus === 'invalid') return { error: 'Invalid API key', statusCode: 401 };
    if (!current.user && current.apiKeyStatus !== 'valid') return { error: 'Login or CAIt API key required', statusCode: 401 };
    const jobId = String(body.job_id || body.jobId || '').trim();
    if (!jobId) return { error: 'job_id required', statusCode: 400 };
    const state = await storage.getState();
    const job = Array.isArray(state.jobs) ? state.jobs.find((item) => String(item?.id || '') === jobId) : null;
    if (!job || !canViewJobFromRequest(state, current, env, job, request)) {
      return { error: 'Job not found or access denied', statusCode: 404 };
    }
    const runningFollowup = body.running === true || body.allow_running === true || body.allowRunning === true || body.mode === 'running';
    if (String(job.status || '') !== 'completed' && !runningFollowup) {
      return { error: 'Follow-up orders can be prepared after a delivery is completed.', statusCode: 400 };
    }
    if (String(job.status || '') !== 'completed') return buildRunningOrderFollowupOrderBody(job, body);
    const directFollowup = body.direct === true || body.direct_followup === true || body.mode === 'direct';
    if (directFollowup && !String(job.assignedAgentId || '').trim()) {
      return { error: 'This delivery has no direct assigned agent. Open it in CAIt Chat and route the follow-up manually.', statusCode: 400 };
    }
    return buildGenericDeliveryFollowupOrderBody(job, body);
  }

  async function executeGithubExecutorPullRequest(storage, current, body, env, request = null) {
    if (!current.user && current.apiKeyStatus === 'invalid') return { error: 'Invalid API key', statusCode: 401 };
    if (!current.user && current.apiKeyStatus !== 'valid') return { error: 'Login or CAIt API key required', statusCode: 401 };
    if (!sessionHasGithubApp(current.session) && current.apiKeyStatus !== 'valid') {
      return {
        error: 'GitHub App login required to create executor PRs.',
        use: '/auth/github',
        statusCode: 403
      };
    }
    if (!body.owner || !body.repo) return { error: 'owner and repo required', statusCode: 400 };
    if (!String(body.content || '').trim()) return { error: 'content required', statusCode: 400 };
    if (current.apiKeyStatus === 'valid' && !hasRepoWriteConfirmation(body)) {
      return {
        error: 'Repository write confirmation required for CAIT_API_KEY executor PR creation.',
        required: 'Set confirm_repo_write=true after showing the target repository, branch, files, and PR action to the user.',
        repo: `${body.owner}/${body.repo}`,
        use: '/chat.html',
        statusCode: 409
      };
    }
    try {
      const repoAccess = await githubAppRepoTokenForRequester(current, body.owner, body.repo, body.installation_id || '', env);
      if (repoAccess.error) return { error: repoAccess.error, use: repoAccess.use, next_step: repoAccess.next_step, statusCode: repoAccess.statusCode || 403 };
      const { selectedRepo, installationToken } = repoAccess;
      const repoMetaResult = await fetchGithubRepoMeta(body.owner, body.repo, installationToken);
      if (!repoMetaResult.ok) return { error: repoMetaResult.error, statusCode: repoMetaResult.status === 404 ? 404 : 400 };
      const repoMeta = repoMetaResult.repo;
      const plan = githubExecutorPlanFromRequest(body, repoMeta);
      const baseSha = await fetchGithubBranchSha(installationToken, body.owner, body.repo, repoMeta.default_branch);
      if (!baseSha.ok || !baseSha.sha) {
        return { error: baseSha.error || `Could not resolve ${repoMeta.default_branch}`, statusCode: 400 };
      }
      const branchCreated = await createGithubBranch(installationToken, body.owner, body.repo, plan.branchName, baseSha.sha);
      if (!branchCreated.ok) {
        return { ...githubPermissionError(branchCreated, 'Could not create executor branch'), statusCode: branchCreated.status === 422 ? 409 : 400 };
      }
      const existing = await fetchGithubTextFile(installationToken, body.owner, body.repo, plan.filePath, repoMeta.default_branch);
      if (existing.ok && existing.text && !existing.text.includes(GITHUB_EXECUTOR_MARKER) && !existing.text.includes(GITHUB_ADAPTER_MARKER)) {
        return {
          error: `Refusing to overwrite existing non-AIagent2 file at ${plan.filePath}.`,
          path: plan.filePath,
          branch: plan.branchName,
          statusCode: 409
        };
      }
      const write = await upsertGithubTextFile(installationToken, body.owner, body.repo, {
        path: plan.filePath,
        branch: plan.branchName,
        content: plan.fileContent,
        sha: existing.ok ? existing.sha : '',
        message: existing.ok ? `Update ${PRODUCT_SHORT_NAME} executor handoff: ${plan.filePath}` : `Add ${PRODUCT_SHORT_NAME} executor handoff: ${plan.filePath}`
      });
      if (!write.ok) {
        return { ...githubPermissionError(write, `Could not write ${plan.filePath}`), statusCode: write.status === 422 ? 409 : 400 };
      }
      const pull = await createGithubPullRequest(installationToken, body.owner, body.repo, {
        title: plan.prTitle,
        body: plan.prBody,
        head: plan.branchName,
        base: repoMeta.default_branch
      });
      if (!pull.ok) {
        return { ...githubPermissionError(pull, 'Could not create executor pull request'), statusCode: pull.status === 422 ? 409 : 400 };
      }
      await touchEvent(storage, 'UPDATED', `Executor PR created for ${repoMeta.full_name}: ${pull.pullRequest.htmlUrl}`, {
        repo: repoMeta.full_name,
        branch: plan.branchName,
        pr: pull.pullRequest.htmlUrl,
        kind: plan.kind
      });
      if (current.apiKey?.id && request) await recordOrderApiKeyUsage(storage, current, request);
      return {
        ok: true,
        auth_provider: 'github-app',
        access_mode: current.apiKeyStatus === 'valid' ? 'account-stored-installation' : 'installation-selected',
        repo: { fullName: repoMeta.full_name, private: repoMeta.private },
        installation_id: selectedRepo.installationId,
        executor_kind: plan.kind,
        branch: plan.branchName,
        base_branch: repoMeta.default_branch,
        files: [{ path: plan.filePath, commit_sha: write.commitSha }],
        pull_request: pull.pullRequest,
        next_step: 'Review the PR handoff file in GitHub, then continue implementation in the repository workflow.',
        statusCode: 201
      };
    } catch (error) {
      return { ...githubPermissionError(error), statusCode: 500 };
    }
  }

  async function executeDeliveryActionRequest(storage, request, env) {
    const body = await parseBody(request).catch((error) => ({ __error: error.message }));
    if (body.__error) return { error: body.__error, statusCode: 400 };
    const current = await currentAgentRequesterContext(storage, request, env);
    if (!current?.user && current.apiKeyStatus === 'invalid') return { error: 'Invalid API key', statusCode: 401 };
    if (!current?.user && current.apiKeyStatus !== 'valid') return { error: 'Login or CAIt API key required', statusCode: 401 };
    const writeAccess = requireOrderWriteAccess(current, env);
    if (writeAccess.error) return { error: writeAccess.error, statusCode: writeAccess.statusCode || 400 };
    const jobId = String(body.job_id || body.jobId || '').trim();
    const state = await storage.getState();
    if (jobId) {
      const job = Array.isArray(state.jobs) ? state.jobs.find((item) => String(item?.id || '') === jobId) : null;
      if (!job || !canViewJobFromRequest(state, current, env, job, request)) return { error: 'Job not found or access denied', statusCode: 404 };
    }
    const actionKind = String(body.action_kind || body.actionKind || '').trim();
    if (!actionKind) return { error: 'action_kind required', statusCode: 400 };
    if (!isDeliveryExecutionActionSupported(actionKind)) {
      return { error: 'Unsupported delivery execute action.', statusCode: 400, action_kind: actionKind };
    }
    const executionConfirmationRequirement = deliveryExecutionConfirmationRequirement(actionKind);
    if (executionConfirmationRequirement && !hasDeliveryExecutionConfirmation(body)) {
      return {
        error: 'Explicit confirmation required before executing this action.',
        required: executionConfirmationRequirement,
        action_kind: actionKind,
        statusCode: 428
      };
    }
    const actionPayload = deliveryExecutorActionPayload(body);
    if (actionPayload) {
      const result = await executeScheduledExactConnectorAction(storage, env, {
        id: jobId || crypto.randomUUID(),
        input: { _broker: { exactConnectorAction: actionPayload } }
      }, current);
      return result?.ok
        ? { ...normalizeDeliveryExecuteResponse(result, actionKind), statusCode: 200 }
        : { ...(result || { error: 'Execution failed' }), statusCode: result?.statusCode || 400 };
    }
    if (actionKind === 'github_pr') {
      const draft = body.draft && typeof body.draft === 'object' ? body.draft : {};
      const deliverable = body.deliverable && typeof body.deliverable === 'object' ? body.deliverable : {};
      const repoFullName = String(draft.repoFullName || '').trim();
      if (!repoFullName.includes('/')) return { error: 'Select the GitHub repository first.', statusCode: 400, action_kind: actionKind };
      const [owner, repo] = repoFullName.split('/');
      const result = await executeGithubExecutorPullRequest(storage, current, {
        owner,
        repo,
        installation_id: body.installation_id || body.installationId || '',
        confirm_repo_write: true,
        kind: String(body.kind || draft.kind || deliverable.kind || 'code_handoff').trim() || 'code_handoff',
        repo_path: String(body.repo_path || body.repoPath || draft.repoPath || '').trim(),
        source_job_id: jobId,
        source_delivery_title: String(deliverable.title || ''),
        source_file_name: String(deliverable.fileName || ''),
        title: String(deliverable.title || 'Code handoff'),
        content: String(deliverable.content || ''),
        execution_mode: String(draft.executionMode || 'draft_pr')
      }, env, request);
      return result?.ok
        ? { ...normalizeDeliveryExecuteResponse(result, actionKind), statusCode: result.statusCode || 200 }
        : result;
    }
    if (actionKind === 'report_next') {
      const orderCurrent = await currentOrderRequesterContext(storage, request, env);
      const access = requireOrderWriteAccess(orderCurrent, env);
      if (access.error) return { error: access.error, statusCode: access.statusCode || 400, action_kind: actionKind };
      const job = Array.isArray(state.jobs) ? state.jobs.find((item) => String(item?.id || '') === jobId) : null;
      if (!job) return { error: 'Job not found', statusCode: 404, action_kind: actionKind };
      const draft = body.draft && typeof body.draft === 'object' ? body.draft : {};
      const deliverable = body.deliverable && typeof body.deliverable === 'object' ? body.deliverable : {};
      const nextBody = buildReportNextOrderBody(job, deliverable, draft);
      if (String(draft.nextStep || '').trim() === 'action_plan') {
        return { error: 'Action plan mode prepares the next step but does not auto-run it.', statusCode: 400, action_kind: actionKind };
      }
      const promptInjection = promptInjectionGuardForPrompt(nextBody.prompt);
      const touchUsage = async () => {
        if (orderCurrent.apiKey?.id) await recordOrderApiKeyUsage(storage, orderCurrent, request);
      };
      if (promptInjection.blocked) {
        await touchUsage();
        return { ...promptPolicyBlockPayload(promptInjection), statusCode: 400, action_kind: actionKind };
      }
      const requestedStrategy = normalizeOrderStrategy(nextBody.order_strategy || nextBody.orderStrategy || nextBody.execution_mode || nextBody.executionMode);
      const resolved = resolveOrderStrategy(state.agents || [], nextBody, requestedStrategy);
      const guestPrepared = await prepareGuestTrialOrderContext(storage, orderCurrent, nextBody, resolved);
      if (guestPrepared.error) return guestPrepared;
      const preparedCurrent = guestPrepared.current;
      const preparedBody = guestPrepared.body;
      const result = resolved.strategy === 'multi'
        ? await handleCreateWorkflowJob(storage, request, env, preparedCurrent, preparedBody, { touchUsage, workflowPlan: resolved.plan, asyncDispatch: true, initialState: state })
        : await performSingleJobCreate(storage, env, preparedCurrent, preparedBody, { touchUsage, request, asyncDispatch: true });
      if (result?.error) return result;
      return {
        ...normalizeDeliveryExecuteResponse({
          ...result,
          order_strategy_requested: requestedStrategy,
          order_strategy_resolved: resolved.strategy,
          routing_reason: resolved.reason,
          routing_planned_task_types: resolved.plan?.plannedTasks || undefined
        }, actionKind),
        statusCode: result.statusCode || 201
      };
    }
    return {
      error: `Delivery action "${actionKind}" is configured but has no execution handler.`,
      code: 'delivery_action_handler_missing',
      statusCode: 500,
      action_kind: actionKind
    };
  }

  async function scheduleDeliveryActionRequest(storage, request, env) {
    const body = await parseBody(request).catch((error) => ({ __error: error.message }));
    if (body.__error) return { error: body.__error, statusCode: 400 };
    const current = await currentOrderRequesterContext(storage, request, env);
    const access = requireOrderWriteAccess(current, env);
    if (access.error) return { error: access.error, statusCode: access.statusCode || 400 };
    const jobId = String(body.job_id || body.jobId || '').trim();
    const state = await storage.getState();
    if (jobId) {
      const job = Array.isArray(state.jobs) ? state.jobs.find((item) => String(item?.id || '') === jobId) : null;
      if (!job || !canViewJobFromRequest(state, current, env, job, request)) return { error: 'Job not found or access denied', statusCode: 404 };
    }
    const actionKind = String(body.action_kind || body.actionKind || '').trim();
    if (!actionKind || !isDeliveryScheduleActionSupported(actionKind)) {
      return { error: 'Unsupported delivery schedule action.', statusCode: 400, action_kind: actionKind };
    }
    const action = deliveryExecutorActionPayload(body);
    if (!action || String(action.kind || '').trim() !== actionKind) {
      return {
        error: `Delivery action "${actionKind}" is configured but has no schedule handler.`,
        code: 'delivery_action_handler_missing',
        statusCode: 500,
        action_kind: actionKind
      };
    }
    const scheduleConfirmationRequirement = deliveryScheduleConfirmationRequirement(actionKind);
    if (scheduleConfirmationRequirement && !hasDeliveryScheduleConfirmation(body)) {
      return {
        error: 'Explicit confirmation required before scheduling this action.',
        required: scheduleConfirmationRequirement,
        action_kind: actionKind,
        statusCode: 428
      };
    }
    const scheduledFor = String(body.scheduled_for || body.scheduledFor || '').trim();
    if (!Number.isFinite(Date.parse(scheduledFor))) return { error: 'Choose a valid future schedule time first.', statusCode: 400, action_kind: String(action.kind || '') };
    if (Date.parse(scheduledFor) <= Date.now() + 60_000) return { error: 'Choose a schedule time at least one minute in the future.', statusCode: 400, action_kind: String(action.kind || '') };
    const deliverable = body.deliverable && typeof body.deliverable === 'object' ? body.deliverable : {};
    const taskType = String(body.task_type || body.taskType || (action.kind === 'x_post' ? 'x_post' : action.kind === 'instagram_post' ? 'instagram' : 'email_ops')).trim();
    const recurringBody = {
      parent_agent_id: String(body.parent_agent_id || body.parentAgentId || 'cloudcode-main'),
      task_type: taskType,
      order_strategy: 'single',
      prompt: String(body.prompt || `${deliverable.title || 'Scheduled action'}\nScheduled for ${scheduledFor}`),
      next_run_at: scheduledFor,
      max_runs: 1,
      schedule: {
        interval: 'daily',
        time: '09:00',
        timezone: String(body.timezone || 'Asia/Tokyo')
      },
      input: {
        _broker: {
          exactConnectorAction: {
            ...action,
            scheduledFor,
            previewText: String(body.preview_text || body.previewText || '')
          }
        }
      }
    };
    const promptInjection = promptInjectionGuardForPrompt(recurringBody.prompt || '');
    if (promptInjection.blocked) {
      if (current.apiKey?.id) await recordOrderApiKeyUsage(storage, current, request);
      return promptPolicyBlockPayload(promptInjection);
    }
    let result = null;
    await storage.mutate(async (draft) => {
      result = createRecurringOrderInState(draft, recurringBody, current);
    });
    if (result?.error) return result;
    await touchEvent(storage, 'RECURRING', `scheduled work ${result.recurringOrder.id.slice(0, 12)} created`, {
      recurringOrderId: result.recurringOrder.id,
      ownerLogin: current.login,
      interval: result.recurringOrder.schedule?.interval || 'daily',
      nextRunAt: result.recurringOrder.nextRunAt || null
    });
    if (current.apiKey?.id) await recordOrderApiKeyUsage(storage, current, request);
    return { ...normalizeDeliveryScheduleResponse({ recurring_order: result.recurringOrder }, action.kind), statusCode: 201 };
  }

  return {
    executeDeliveryActionRequest,
    prepareDeliveryExecutionRequest,
    prepareDeliveryFollowupOrderRequest,
    prepareDeliveryPublishOrderRequest,
    prepareDeliveryPublishRequest,
    scheduleDeliveryActionRequest
  };
}
