import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { existsSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const htmlPath = new URL('../public/index.html', import.meta.url);
const chatHtmlPath = new URL('../public/chat.html', import.meta.url);
const loginHtmlPath = new URL('../public/login.html', import.meta.url);
const adminHtmlPath = new URL('../public/admin.html', import.meta.url);
const appsHtmlPath = new URL('../public/apps.html', import.meta.url);
const appsJsPath = new URL('../public/apps.js', import.meta.url);
const analyticsHtmlPath = new URL('../public/analytics-console.html', import.meta.url);
const publisherHtmlPath = new URL('../public/publisher-approval.html', import.meta.url);
const leadOpsHtmlPath = new URL('../public/lead-ops.html', import.meta.url);
const deliveryManagerHtmlPath = new URL('../public/delivery-manager.html', import.meta.url);
const legalNoticeHtmlPath = new URL('../public/legal-notice.html', import.meta.url);
const tokushohoRedirectHtmlPath = new URL('../public/tokushoho.html', import.meta.url);
const siteMapHtmlPath = new URL('../public/site-map.html', import.meta.url);
const homeCssPath = new URL('../public/home.css', import.meta.url);
const appConsoleCssPath = new URL('../public/app-console.css', import.meta.url);
const adminCssPath = new URL('../public/admin.css', import.meta.url);
const adminJsPath = new URL('../public/admin.js', import.meta.url);
const clientJsPath = new URL('../public/client.js', import.meta.url);
const analyticsLoaderPath = new URL('../public/analytics-loader.js', import.meta.url);
const chatJsPath = new URL('../public/chat.js', import.meta.url);
const analyticsJsPath = new URL('../public/analytics-console.js', import.meta.url);
const publisherJsPath = new URL('../public/publisher-approval.js', import.meta.url);
const leadOpsJsPath = new URL('../public/lead-ops.js', import.meta.url);
const deliveryManagerJsPath = new URL('../public/delivery-manager.js', import.meta.url);
const caitAppBridgePath = new URL('../public/cait-app-bridge.js', import.meta.url);
const loginJsPath = new URL('../public/login.js', import.meta.url);
const chatCssPath = new URL('../public/chat.css', import.meta.url);
const stylesCssPath = new URL('../public/styles.css', import.meta.url);
const chatEnginePath = new URL('../public/chat-engine.js', import.meta.url);
const deliveryActionContractPath = new URL('../public/delivery-action-contract.js', import.meta.url);
const workerPath = new URL('../worker.js', import.meta.url);
const serverPath = new URL('../server.js', import.meta.url);
const mcpPath = new URL('../lib/mcp.js', import.meta.url);
const httpPolicyPath = new URL('../lib/http-policy.js', import.meta.url);
const wranglerPath = new URL('../wrangler.jsonc', import.meta.url);
const publicHeadersPath = new URL('../public/_headers', import.meta.url);

execFileSync(process.execPath, ['--check', fileURLToPath(chatJsPath)], { stdio: 'pipe' });
execFileSync(process.execPath, ['--check', fileURLToPath(appsJsPath)], { stdio: 'pipe' });
execFileSync(process.execPath, ['--check', fileURLToPath(loginJsPath)], { stdio: 'pipe' });
execFileSync(process.execPath, ['--check', fileURLToPath(adminJsPath)], { stdio: 'pipe' });
execFileSync(process.execPath, ['--check', fileURLToPath(clientJsPath)], { stdio: 'pipe' });
execFileSync(process.execPath, ['--check', fileURLToPath(analyticsLoaderPath)], { stdio: 'pipe' });
execFileSync(process.execPath, ['--check', fileURLToPath(analyticsJsPath)], { stdio: 'pipe' });
execFileSync(process.execPath, ['--check', fileURLToPath(publisherJsPath)], { stdio: 'pipe' });
execFileSync(process.execPath, ['--check', fileURLToPath(leadOpsJsPath)], { stdio: 'pipe' });
execFileSync(process.execPath, ['--check', fileURLToPath(deliveryManagerJsPath)], { stdio: 'pipe' });
execFileSync(process.execPath, ['--check', fileURLToPath(caitAppBridgePath)], { stdio: 'pipe' });
execFileSync(process.execPath, ['--check', fileURLToPath(chatEnginePath)], { stdio: 'pipe' });
execFileSync(process.execPath, ['--check', fileURLToPath(deliveryActionContractPath)], { stdio: 'pipe' });
execFileSync(process.execPath, ['--check', fileURLToPath(mcpPath)], { stdio: 'pipe' });
execFileSync(process.execPath, ['--check', fileURLToPath(httpPolicyPath)], { stdio: 'pipe' });

const html = readFileSync(htmlPath, 'utf8');
const chatHtml = readFileSync(chatHtmlPath, 'utf8');
const loginHtml = readFileSync(loginHtmlPath, 'utf8');
const adminHtml = readFileSync(adminHtmlPath, 'utf8');
const appsHtml = readFileSync(appsHtmlPath, 'utf8');
const appsJs = readFileSync(appsJsPath, 'utf8');
const analyticsHtml = readFileSync(analyticsHtmlPath, 'utf8');
const publisherHtml = readFileSync(publisherHtmlPath, 'utf8');
const leadOpsHtml = readFileSync(leadOpsHtmlPath, 'utf8');
const deliveryManagerHtml = readFileSync(deliveryManagerHtmlPath, 'utf8');
const legalNoticeHtml = readFileSync(legalNoticeHtmlPath, 'utf8');
const tokushohoRedirectHtml = readFileSync(tokushohoRedirectHtmlPath, 'utf8');
const siteMapHtml = readFileSync(siteMapHtmlPath, 'utf8');
const homeCss = readFileSync(homeCssPath, 'utf8');
const appConsoleCss = readFileSync(appConsoleCssPath, 'utf8');
const adminCss = readFileSync(adminCssPath, 'utf8');
const adminJs = readFileSync(adminJsPath, 'utf8');
const clientJs = readFileSync(clientJsPath, 'utf8');
const analyticsLoaderJs = readFileSync(analyticsLoaderPath, 'utf8');
const chatJs = readFileSync(chatJsPath, 'utf8');
const analyticsJs = readFileSync(analyticsJsPath, 'utf8');
const publisherJs = readFileSync(publisherJsPath, 'utf8');
const leadOpsJs = readFileSync(leadOpsJsPath, 'utf8');
const deliveryManagerJs = readFileSync(deliveryManagerJsPath, 'utf8');
const caitAppBridge = readFileSync(caitAppBridgePath, 'utf8');
const loginJs = readFileSync(loginJsPath, 'utf8');
const chatEngine = readFileSync(chatEnginePath, 'utf8');
const chatCss = readFileSync(chatCssPath, 'utf8');
const stylesCss = readFileSync(stylesCssPath, 'utf8');
const worker = readFileSync(workerPath, 'utf8');
const server = readFileSync(serverPath, 'utf8');
const mcp = readFileSync(mcpPath, 'utf8');
const httpPolicy = readFileSync(httpPolicyPath, 'utf8');
const wrangler = readFileSync(wranglerPath, 'utf8');
const publicHeaders = readFileSync(publicHeadersPath, 'utf8');
const appSurfaceSources = [
  appsHtml,
  appsJs,
  analyticsHtml,
  analyticsJs,
  publisherHtml,
  publisherJs,
  leadOpsHtml,
  leadOpsJs,
  deliveryManagerHtml,
  deliveryManagerJs,
  caitAppBridge
].join('\n');

assert.equal(existsSync(fileURLToPath(new URL('../public/chatux/', import.meta.url))), false, '/chatux static directory should be removed');

assert.ok(html.includes('<main class="home-shell" aria-label="CAIt landing page">'), 'Root page should be the public landing page.');
assert.ok(html.includes('Anyone can create high-quality AI agent output'), 'Root should lead with anyone-can-create-high-quality-output positioning.');
assert.ok(html.includes('scheduled work continue in the background'), 'Root should mention background scheduled work as supporting value, not the primary headline.');
assert.ok(html.includes('/home.css?v=20260504b'), 'Root should load the home landing CSS.');
assert.ok(html.includes('<p class="hero-read">'), 'Root hero should include a short read line between the catch and START.');
assert.ok(html.includes('href="/login?next=%2Fchat&amp;source=start"'), 'Root START should send users to the dedicated login screen.');
assert.ok(!html.includes('/auth/google?return_to=%2Fchat.html'), 'Root should not embed provider login buttons or OAuth links.');
assert.ok(html.includes('class="primary-action start-action"'), 'Root should expose one prominent START action.');
assert.equal((html.match(/class="primary-action/g) || []).length, 1, 'Root should only have one prominent primary action.');
assert.ok(!html.includes('href="/chat.html"'), 'Root should not link directly to chat; START should go through the dedicated login screen.');
assert.ok(html.includes('<nav class="home-links" aria-label="CAIt pages">'), 'Root should expose the common public navigation in the landing header.');
assert.ok(html.includes('href="/login?next=%2Fchat&amp;source=nav"'), 'Root header Chat link should route through login.');
assert.ok(html.includes('href="/apps.html"'), 'Root should expose the new CAIt app hub.');
assert.ok(html.includes('href="/delivery-manager.html"'), 'Root header should expose the built-in Deliveries feature.');
assert.ok(html.includes('href="/legal-notice.html"'), 'Root footer should link to the legal notice disclosure.');
assert.ok(html.includes('Legal Notice (SCTA)'), 'Root footer should use a concise global legal notice label.');
assert.ok(!html.includes('href="/tokushoho.html"'), 'Root footer should not use the Japanese romanized legal notice URL.');
assert.ok(legalNoticeHtml.includes('株式会社ビジネスラボ'), 'Legal notice disclosure should show the legal seller name.');
assert.ok(legalNoticeHtml.includes('6120901008074'), 'Legal notice disclosure should show the corporate number.');
assert.ok(legalNoticeHtml.includes('東京都中央区銀座1丁目12番4号'), 'Legal notice disclosure should show the registered address.');
assert.ok(legalNoticeHtml.includes('Act on Specified Commercial Transactions'), 'Legal notice disclosure should include the official English act name.');
assert.ok(legalNoticeHtml.includes('Business Labo Co., Ltd.'), 'Legal notice disclosure should include English seller context.');
assert.ok(legalNoticeHtml.includes('Cancellation and Refunds'), 'Legal notice disclosure should include English field labels.');
assert.ok(legalNoticeHtml.includes('https://aiagent-marketplace.net/legal-notice.html'), 'Legal notice should canonicalize to the English URL.');
assert.ok(tokushohoRedirectHtml.includes('/legal-notice.html'), 'Old tokushoho URL should redirect to the English legal notice URL.');
assert.ok(siteMapHtml.includes('https://aiagent-marketplace.net/legal-notice.html'), 'Site map structured data should use the English legal notice URL.');
assert.ok(siteMapHtml.includes('href="/legal-notice.html"'), 'Site map HTML should use the English legal notice URL.');
assert.ok(!html.includes('id="promptInput"'), 'Root should not render the chat composer.');
assert.ok(!html.includes('type="module" src="/chat.js'), 'Root should not load chat JS.');
assert.ok(chatHtml.includes('<main class="chatux-shell" aria-label="CAIt chat">'), 'Chat page should render the chat-first CAIt UI.');
assert.ok(chatHtml.includes('/chat.css?v=20260510b'), 'Chat page should load root chat CSS, not /chatux assets.');
assert.ok(/type="module"\s+src="\/chat\.js\?v=20260511[a-z0-9]+"/.test(chatHtml), 'Chat page should load root chat JS, not /chatux assets.');
assert.ok(chatHtml.includes('What do you want done?'), 'Chat should open with a short English prompt instead of a long routing explanation.');
assert.ok(!chatHtml.includes('何がしたいですか？'), 'Chat should not default to Japanese copy.');
assert.ok(!chatHtml.includes('CAIt will route simple work'), 'Chat should not lead with routing mechanics.');
assert.ok(chatHtml.includes('id="chatThread"'));
assert.ok(chatHtml.includes('id="promptInput"'));
assert.ok(chatHtml.includes('id="chatSessionSidebar"'), 'Chat should render a left chat session sidebar.');
assert.ok(chatHtml.includes('id="chatSessionList"'), 'Chat should render a restorable chat session list.');
assert.ok(chatHtml.includes('id="newChatBtn"'), 'Chat should expose a New chat action in the session sidebar.');
assert.ok(chatHtml.includes('id="openScheduleBtn"'), 'Chat should expose a compact schedule button.');
assert.ok(chatHtml.includes('id="openScheduleComposerBtn"'), 'Chat should expose scheduled work next to the chat composer.');
assert.ok(chatHtml.includes('class="chatux-nav"'), 'Chat should expose links to existing pages.');
assert.ok(chatHtml.includes('href="/delivery-manager.html"'), 'Chat header should link to the built-in Deliveries feature.');
assert.ok(chatHtml.includes('href="/admin" id="adminNavLink" hidden'), 'Chat should expose an admin link only when admin auth reveals it.');
assert.ok(chatJs.includes('appendThinkingMessage'), 'Chat should show a transient thinking state while OpenAI intent classification is running.');
assert.ok(chatJs.includes('Thinking...'), 'Chat thinking state should use English copy on the English chat page.');
assert.ok(chatJs.includes('removeMessage(thinkingMessage)'), 'Chat should remove the transient thinking state after OpenAI returns or fails.');
assert.ok(chatJs.includes('conversationLanguage'), 'Chat should remember the language of the first user input for the conversation.');
assert.ok(chatJs.includes('rememberConversationLanguage(prompt)'), 'Chat should set the conversation language from the first submitted prompt.');
assert.ok(chatJs.includes('PROMPT_PLACEHOLDERS'), 'Chat composer placeholders should be able to follow the selected conversation language.');
assert.ok(chatJs.includes('CAIt will not keep asking after this round'), 'Leader intake should tell users it will not repeat after the current round.');
assert.ok(chatJs.includes('growthLeaderNeedsDataHint'), 'Growth leader intake should point users toward connectors or source URLs instead of asking repeated data questions.');
assert.ok(chatJs.includes('Connected Google analytics can be attached'), 'Growth order checks should surface connected Google analytics instead of silently skipping it.');
assert.ok(chatJs.includes('Analytics was skipped for this prepared order'), 'Growth order checks should allow an explicit analytics skip only when the user chooses it.');
assert.ok(clientJs.includes("if (requested.length) url.searchParams.set('capabilities', requested.join(','))"), 'Chat Google connector should pass exact required Google capabilities into OAuth without adding broad defaults.');
assert.ok(clientJs.includes("data-connector-capabilities"), 'Connector action buttons should carry the exact capability requested by the blocked action.');
assert.ok(chatJs.includes('googleAuthorityConnectGroups'), 'Chat Google approval should connect every requested Google source in one OAuth popup.');
assert.ok(chatJs.includes('Connect GA4 + Search Console'), 'Chat Google approval should label combined GA4/Search Console requests clearly.');
assert.ok(chatJs.includes('function xConnectLinkHtml'), 'Chat X connector links should be centralized for approval cards and action cards.');
assert.ok(chatJs.includes('data-chat-oauth-popup="x"'), 'Chat X connector approval should open OAuth in a popup and keep the current order attached.');
assert.ok(chatJs.includes('Resume X approval'), 'X authority cards should expose a functional resume action after the connector is ready.');
assert.ok(!chatJs.includes('href="${escapeHtml(openWorkHref)}"'), 'Open chat approval must not be a no-op anchor back to the same card.');
assert.ok(chatJs.includes("source === 'leader_execution_approval' && status !== 'blocked'"), 'Future leader execution approval hints should not render as active chat approvals before the workflow is blocked.');
assert.ok(chatJs.includes('Progress check temporarily failed'), 'Chat progress polling should retry transient 503-style failures instead of stopping the order.');
assert.ok(chatJs.includes('answerSaysAnalyticsAvailable'), 'Chat intake should detect when the user says GA4/Search Console is available.');
assert.ok(chatJs.includes('openAnalyticsConsoleForIntake'), 'Chat intake should open Analytics Console before dispatch when analytics data is available.');
assert.ok(chatJs.includes('openAnalyticsConsoleForDraft'), 'Chat order checks should open Analytics Console and attach returned context to the prepared draft.');
assert.ok(chatJs.includes('attachAppContextToDraft'), 'Returned app context should attach to the current draft instead of only filling the composer.');
assert.ok(chatJs.includes('choose the GA4 property and Search Console site'), 'Chat should instruct users to identify the exact analytics account, property, and site.');
assert.ok(chatJs.includes('analyticsIntakeChoiceHtml'), 'Chat intake should render explicit analytics choice buttons.');
assert.ok(chatJs.includes('data-chat-action="analytics-use"'), 'Chat intake should include a button to use GA4/Search Console.');
assert.ok(chatJs.includes('data-chat-action="analytics-skip"'), 'Chat intake should include a button to skip GA4/Search Console.');
assert.ok(chatJs.includes('intakeChoiceGroups'), 'Chat intake should use generic concrete choice groups, not one-off question cards.');
assert.ok(chatJs.includes('data-intake-choice'), 'Chat intake choices should be clickable buttons that fill the answer composer.');
assert.ok(chatJs.includes('data-intake-other-input'), 'Chat intake should allow free-text Other answers inside each choice group.');
assert.ok(chatJs.includes('data-intake-other-add'), 'Chat intake should add free-text Other answers to the composer.');
assert.ok(chatJs.includes('data-intake-confirmed-list'), 'Chat intake should show confirmed answers below each choice group.');
assert.ok(chatJs.includes('data-intake-confirmed-edit'), 'Chat intake confirmed answers should be editable.');
assert.ok(chatJs.includes('data-intake-confirmed-remove'), 'Chat intake confirmed answers should be removable.');
assert.ok(chatJs.includes('removeIntakeChoiceFromComposer'), 'Removing a confirmed intake answer should remove it from the composer.');
assert.ok(chatJs.includes('Click one or more choices'), 'Chat intake should tell users that multiple choices can be selected.');
assert.ok(chatJs.includes('currentLines.some((line) => line.trim() === nextLine)'), 'Chat intake should append multiple choices without duplicating the same composer line.');
assert.ok(chatJs.includes('Product/service'), 'Chat intake should include a product/service input group when the leader asks what service to sell.');
assert.ok(chatJs.includes('Service name, website/LP URL, or product notes'), 'Chat intake should provide a direct product/service URL free-text field.');
assert.ok(chatJs.includes('No paid ads / organic only'), 'Chat intake should offer concrete constraint choices when the question needs specificity.');
assert.ok(chatJs.includes('Strategy report'), 'Chat intake should offer concrete output format choices when delivery format is unclear.');
assert.ok(chatJs.includes('/api/recurring-orders'), 'Chat should create and manage recurring orders from the schedule panel.');
assert.ok(chatJs.includes('showSchedulePanel'), 'Chat should render a scheduled-work utility panel.');
assert.ok(chatJs.includes('openScheduleComposerBtn'), 'Chat composer schedule button should open the scheduled-work panel.');
assert.ok(chatJs.includes('Completed order to rerun'), 'Chat schedules should be based on completed orders, not unconfirmed free-text requests.');
assert.ok(chatJs.includes('buildScheduledJobPayloadFromCompletedOrder'), 'Chat should build schedules from a completed order payload.');
assert.ok(chatJs.includes('reused_completed_order'), 'Scheduled reruns should preserve that intake already happened on the source order.');
assert.ok(chatJs.includes('createScheduleFromForm'), 'Chat should schedule a selected completed order from the clock panel.');
assert.ok(chatJs.includes('requestSubmit()'), 'Chat should submit with Ctrl+Enter/Cmd+Enter from the composer.');
assert.ok(chatJs.includes('chat_required: false'), 'Scheduled chat work should be marked as background work that does not require the chat to stay open.');
assert.ok(chatJs.includes('renderChatSessionSidebar'), 'Chat should render a ChatGPT-style session sidebar.');
assert.ok(chatJs.includes('refreshChatSessionHistory'), 'Chat should restore signed-in chat history from the server.');
assert.ok(chatJs.includes('function applyAuthState'), 'Chat memory should hydrate lightweight auth without waiting for /auth/status.');
assert.ok(chatJs.indexOf('void refreshChatSessionHistory({ force: true });') < chatJs.indexOf('void refreshAuth();'), 'Chat should start loading the session list before the full auth status request.');
assert.ok(chatJs.includes("return '/api/chat-memory'"), 'Chat session history should use the lightweight chat-memory API instead of the full snapshot.');
assert.ok(!chatJs.includes("return '/api/snapshot'"), 'Chat session history should not fetch the full snapshot for the sidebar.');
assert.ok(chatJs.includes('Promise.allSettled(ids.map((id) => fetchVisibleJob(id)))'), 'Restored order context should fetch related orders in parallel.');
assert.ok(chatJs.includes('/api/analytics/chat-transcripts'), 'Chat should persist chat turns to the server transcript API.');
assert.ok(chatJs.includes('/api/settings/chat-memory/'), 'Chat sidebar delete should hide server chat memory, not just remove DOM rows.');
assert.ok(chatJs.includes('session_id: chatSessionId'), 'Orders dispatched from chat should carry the active chat session id.');
assert.ok(!chatJs.includes('localStorage.setItem'), 'Chat should not persist chat sessions in browser localStorage.');
assert.ok(chatCss.includes('.chat-session-sidebar'), 'Chat CSS should style the left session sidebar.');
assert.ok(chatCss.includes('.chat-session-row.active'), 'Chat CSS should visibly mark the active chat session.');
assert.ok(chatCss.includes('.message.thinking .message-body'), 'Chat should style the OpenAI thinking state as a visible assistant message.');
assert.ok(chatCss.includes('.utility-form'), 'Chat should style the schedule form inside the utility modal.');
assert.ok(chatCss.includes('.schedule-composer-btn'), 'Chat should keep the composer schedule button stable and visible.');
assert.ok(wrangler.includes('"* * * * *"') && wrangler.includes('"*/15 * * * *"'), 'Cloudflare cron triggers should remain configured for background scheduled work.');
assert.ok(wrangler.includes('"QUEUED_DISPATCH_SWEEP_LIMIT": "12"'), 'Queued dispatch sweep should process enough jobs each minute.');
assert.ok(wrangler.includes('"WORKFLOW_ORCHESTRATION_STALE_MS": "60000"'), 'Workflow watchdog should retry stale queued workflows quickly.');
assert.ok(wrangler.includes('"WORKFLOW_ORCHESTRATION_BLOCKED_MS": "600000"'), 'Workflow watchdog should surface a visible blocker instead of leaving queued forever.');
assert.ok(worker.includes('const layerLimits = new Map'), 'CMO leader task selection should cap upstream work per layer instead of using one global task limit.');
assert.ok(
  worker.includes('[1, 1]')
  && worker.includes('[2, 1]')
  && worker.includes('[3, 1]')
  && worker.includes('[4, actionRequested ? Math.max(1, preparationForRequestedActions.length || 1) : 1]')
  && worker.includes('sourceBucketForTask')
  && worker.includes("preferredCmoSourceTasks.includes('data_analysis')")
  && worker.includes('maxExternalResearchTasks'),
  'Leader upstream layers should keep data/research/planning capped while expanding action-specific preparation.'
);
assert.ok(worker.includes('DISPATCH_SCHEDULE_TIMEOUT_MS'), 'Scheduled dispatch attempts should have a timeout instead of refreshing forever.');
assert.ok(worker.includes('firstDispatchRequestedAt'), 'Dispatch scheduling should preserve the first requested timestamp for stalled-run diagnosis.');
assert.ok(worker.includes('scheduleAttempts'), 'Dispatch scheduling should count scheduling retries separately from agent dispatch attempts.');
assert.ok(loginHtml.includes('CAIt | Sign in or sign up'), 'Login page should be an explicit sign-in/sign-up screen.');
assert.ok(loginHtml.includes('id="loginGoogleBtn"'), 'Login page should offer Google.');
assert.ok(loginHtml.includes('id="loginGithubBtn"'), 'Login page should offer GitHub.');
assert.ok(loginHtml.includes('id="loginEmailInput"'), 'Login page should offer email magic link sign in.');
assert.ok(loginHtml.includes('id="loginTrustNotice"'), 'Login page should show an official sign-in trust notice.');
assert.ok(loginHtml.includes('/home.css?v=20260505b'), 'Login page should use the current light product styling.');
assert.ok(loginHtml.includes('type="module" src="/login.js?v=20260505b"'), 'Login page should load the current login controller.');
assert.ok(loginJs.includes('auth-flash'), 'Login flash should use auth page styling.');
assert.ok(loginJs.includes('CAIT_TRUSTED_AUTH_ORIGIN'), 'Login should know the official CAIt auth origin for local preview users.');
assert.ok(loginJs.includes('runtimeAuthBaseUrl'), 'Login provider links should be able to use the trusted auth origin.');
assert.ok(loginJs.includes('runtimeUsesExternalAuth'), 'Login should keep local-preview provider buttons enabled when official auth is external.');
assert.ok(loginJs.includes('buildOfficialLoginUrl'), 'Email login from local preview should route to official CAIt sign-in.');
assert.ok(loginJs.includes('status?.authBaseUrl'), 'Login should use the server-provided canonical auth base URL.');
assert.ok(loginJs.includes("url.searchParams.set('return_to', postLoginPath(route.next));"), 'Login providers should return to the requested page.');
assert.ok(loginJs.includes("parsed.pathname === '/chat.html'"), 'Login should normalize /chat.html to /chat to avoid asset canonical redirect loops.');
assert.ok(loginJs.includes("parsed.pathname === '/admin.html'"), 'Login should normalize /admin.html to /admin.');
assert.ok(adminHtml.includes('<main class="admin-shell" aria-label="CAIt admin dashboard">'), 'Admin should render a dedicated dashboard shell.');
assert.ok(adminHtml.includes('CAIt Admin'), 'Admin page should be branded as CAIt Admin.');
assert.ok(adminHtml.includes('/admin.css?v=20260510c'), 'Admin should load the current dashboard stylesheet.');
assert.ok(adminHtml.includes('type="module" src="/admin.js?v=20260510c"'), 'Admin should load the dashboard controller.');
assert.ok(adminHtml.includes('id="adminRegistrationsMetric"'), 'Admin should show member registration counts.');
assert.ok(adminHtml.includes('id="accountsTable"'), 'Admin should include a user/account table.');
assert.ok(adminHtml.includes('id="downloadAccountsBtn"'), 'Admin should provide account CSV download.');
assert.ok(adminHtml.includes('href="/delivery-manager.html"'), 'Admin header should link to the built-in Deliveries feature.');
assert.ok(appsHtml.includes('CAIt Apps'), 'Apps hub should list CAIt app consoles.');
assert.ok(appsHtml.includes('href="/delivery-manager.html"'), 'Apps hub header should link to the built-in Deliveries feature.');
assert.ok(appsHtml.includes('data-featured-app-list'), 'Apps hub should render featured workflows from the app registry.');
assert.ok(appsJs.includes('sameOriginAppUrl'), 'Apps hub should normalize built-in app URLs to the current origin.');
assert.ok(appsJs.includes('analytics-console'), 'Apps hub registry rendering should include Analytics Console.');
assert.ok(appsJs.includes('publisher-approval-studio'), 'Apps hub registry rendering should include Publisher and Approval Studio.');
assert.ok(appsJs.includes('lead-ops-console'), 'Apps hub registry rendering should include Lead Ops.');
assert.ok(appsJs.includes('CORE_FEATURE_APP_IDS'), 'Apps hub should filter core CAIt features out of app registry rendering.');
assert.ok(!appsJs.includes("['delivery-manager', { tag: 'Follow-up'"), 'Apps hub should not feature Deliveries as a registered app.');
assert.ok(appsHtml.includes('cait-app-context/v1'), 'Apps hub should explain the shared context contract.');
assert.ok(analyticsHtml.includes('Analytics Console'), 'Analytics Console should be a first-class app page.');
assert.ok(analyticsHtml.includes('href="/apps.html"'), 'Analytics Console should link back to the apps hub.');
assert.ok(analyticsHtml.includes('id="sendContextBtn"'), 'Analytics Console should send context to CAIt.');
assert.ok(analyticsHtml.includes('/analytics-console.js?v=20260511a'), 'Analytics Console should load the app-context receiving controller.');
assert.ok(analyticsHtml.includes('/app-console.css?v=20260507a'), 'Analytics Console should load the current shared app console CSS.');
assert.ok(analyticsHtml.includes('id="analyticsStepSources"'), 'Analytics Console should show a compact workflow state strip.');
assert.ok(analyticsHtml.includes('id="connectGoogleBtn"'), 'Analytics Console should expose a Google OAuth connection button.');
assert.ok(analyticsHtml.includes('id="connectGoogleAllBtn"'), 'Analytics Console should expose a combined GA4 and Search Console OAuth connection button.');
assert.ok(analyticsHtml.includes('href="https://aiagent-marketplace.net/auth/google?action=analytics_connect'), 'Analytics Console connect controls should use real OAuth links, not depend on JS-only click handling.');
assert.ok(analyticsHtml.includes('data-google-connect-link="analytics"'), 'Analytics Console combined connect should be a standard link that requests analytics scopes.');
assert.ok(analyticsHtml.includes('data-google-connect-link="ga4"'), 'Analytics Console GA4 connect should be a standard link that works inside app surfaces.');
assert.ok(analyticsHtml.includes('scope_group=ga4,gsc'), 'Analytics Console combined connect should request GA4 and Search Console together.');
assert.ok(analyticsHtml.includes('scope_group=ga4'), 'Analytics Console GA4 connect should request only the GA4 scope group.');
assert.ok(analyticsHtml.includes('scope_group=gsc'), 'Analytics Console Search Console connect should request only the Search Console scope group.');
assert.ok(analyticsHtml.includes('target="_top"'), 'Analytics Console OAuth links should leave embedded app surfaces and open Google consent in the top page.');
assert.ok(analyticsHtml.includes('id="refreshGoogleSourcesBtn"'), 'Analytics Console should expose a Google source refresh button.');
assert.ok(analyticsHtml.includes('id="loadGoogleReportBtn"'), 'Analytics Console should expose a Google report load button.');
assert.ok(analyticsHtml.includes('id="gscSiteSelect"'), 'Analytics Console should expose a Search Console source selector.');
assert.ok(analyticsHtml.includes('id="ga4PropertySelect"'), 'Analytics Console should expose a GA4 property selector.');
assert.ok(analyticsHtml.includes('id="ga4PropertyInput"'), 'Analytics Console should allow manual GA4 property ID entry when source listing fails.');
assert.ok(analyticsHtml.includes('Channel detail'), 'Analytics Console should keep channel drilldown visible on the same screen.');
assert.ok(!analyticsHtml.includes('id="reportTemplateSelect"'), 'Analytics Console should not require a separate report format selector for channel drilldown.');
assert.ok(!analyticsHtml.includes('id="channelFilterSelect"'), 'Analytics Console should not require a separate channel filter selector for channel drilldown.');
assert.ok(analyticsHtml.includes('id="analyticsQueriesCount"'), 'Analytics Console side navigation counts should come from runtime data.');
assert.ok(publisherHtml.includes('Publisher & Approval'), 'Publisher and Approval Studio should be a first-class app page.');
assert.ok(publisherHtml.includes('href="/apps.html"'), 'Publisher Studio should link back to the apps hub.');
assert.ok(publisherHtml.includes('id="approvalTable"'), 'Publisher Studio should include an approval queue.');
assert.ok(publisherHtml.includes('/publisher-approval.js?v=20260511a'), 'Publisher Studio should load the app-context receiving controller.');
assert.ok(publisherHtml.includes('id="publisherStepApproval"'), 'Publisher Studio should show approval progress before handoff.');
assert.ok(publisherHtml.includes('id="connectGithubBtn"'), 'Publisher Studio should expose GitHub connection.');
assert.ok(publisherHtml.includes('id="repoSelect"'), 'Publisher Studio should expose repository selection.');
assert.ok(publisherHtml.includes('id="createPrBtn"'), 'Publisher Studio should expose PR handoff creation.');
assert.ok(publisherHtml.includes('id="publisherDestinationCount"'), 'Publisher Studio side navigation counts should come from runtime data.');
assert.ok(leadOpsHtml.includes('Lead Ops'), 'Lead Ops should be a first-class app page.');
assert.ok(leadOpsHtml.includes('href="/apps.html"'), 'Lead Ops should link back to the apps hub.');
assert.ok(leadOpsHtml.includes('id="sendLeadContextBtn"'), 'Lead Ops should send context to CAIt.');
assert.ok(leadOpsHtml.includes('/lead-ops.js?v=20260511a'), 'Lead Ops should load the app-context receiving controller.');
assert.ok(leadOpsHtml.includes('id="approveLeadBtn"'), 'Lead Ops should provide a direct approval action.');
assert.ok(leadOpsHtml.includes('id="scheduleLeadBtn"'), 'Lead Ops should provide scheduled outreach planning.');
assert.ok(leadOpsHtml.includes('id="triggerLeadBtn"'), 'Lead Ops should provide event-triggered outreach planning.');
assert.ok(leadOpsHtml.includes('id="outreachChannelSelect"'), 'Lead Ops should let users choose email, SMS, or other outreach channels.');
assert.ok(leadOpsHtml.includes('id="sendResendBtn"'), 'Lead Ops should execute approved email through CAIt Resend.');
assert.ok(leadOpsHtml.includes('id="scheduleResendBtn"'), 'Lead Ops should schedule approved email through CAIt Resend.');
assert.ok(leadOpsHtml.includes('id="leadAllNavCount"'), 'Lead Ops side navigation counts should come from runtime data.');
assert.ok(deliveryManagerHtml.includes('Deliveries'), 'Deliveries should be a first-class CAIt feature page.');
assert.ok(deliveryManagerHtml.includes('href="/chat"'), 'Deliveries should link back to chat.');
assert.ok(deliveryManagerHtml.includes('id="downloadSelectedBtn"'), 'Delivery Manager should expose downloadable delivery files.');
assert.ok(deliveryManagerHtml.includes('/delivery-manager.js?v=20260511a'), 'Delivery Manager should load the app-context receiving controller.');
assert.ok(deliveryManagerHtml.includes('id="deliverySearchInput"'), 'Delivery Manager should expose delivery search.');
assert.ok(deliveryManagerHtml.includes('id="deliverySortSelect"'), 'Delivery Manager should expose delivery sorting.');
assert.ok(deliveryManagerHtml.includes('data-tab="files"'), 'Delivery Manager should expose file and context tabs.');
assert.ok(deliveryManagerHtml.includes('id="readinessList"'), 'Delivery Manager should show follow-up context readiness.');
assert.ok(deliveryManagerJs.includes('requestedDeliveryIdFromUrl'), 'Delivery Manager should support direct order/job/deep-linked delivery loading.');
assert.ok(deliveryManagerJs.includes('/api/jobs/${encodeURIComponent(safeId)}'), 'Delivery Manager should fetch a deep-linked delivery by job id when it is outside the latest list.');

const builtInAppEntries = [
  {
    name: 'Analytics Console',
    html: analyticsHtml,
    ownScript: '/analytics-console.js',
    forbiddenScripts: ['/publisher-approval.js', '/lead-ops.js', '/delivery-manager.js', '/client.js', '/chat.js']
  },
  {
    name: 'Publisher and Approval Studio',
    html: publisherHtml,
    ownScript: '/publisher-approval.js',
    forbiddenScripts: ['/analytics-console.js', '/lead-ops.js', '/delivery-manager.js', '/client.js', '/chat.js']
  },
  {
    name: 'Lead Ops Console',
    html: leadOpsHtml,
    ownScript: '/lead-ops.js',
    forbiddenScripts: ['/analytics-console.js', '/publisher-approval.js', '/delivery-manager.js', '/client.js', '/chat.js']
  },
  {
    name: 'Delivery Manager',
    html: deliveryManagerHtml,
    ownScript: '/delivery-manager.js',
    forbiddenScripts: ['/analytics-console.js', '/publisher-approval.js', '/lead-ops.js', '/client.js', '/chat.js']
  }
];

for (const app of builtInAppEntries) {
  assert.ok(app.html.includes(`type="module" src="${app.ownScript}`), `${app.name} should load its own dedicated app controller.`);
  for (const forbiddenScript of app.forbiddenScripts) {
    assert.ok(!app.html.includes(`src="${forbiddenScript}`), `${app.name} should not load ${forbiddenScript}; built-in app controllers must stay split by app.`);
  }
}

assert.ok(analyticsJs.includes("source_app: 'analytics_console'"), 'Analytics app logic should stay in analytics-console.js.');
assert.ok(analyticsJs.includes("cait-app-bridge.js?v=20260508e"), 'Analytics Console should load the latest CAIt app bridge.');
assert.ok(caitAppBridge.includes("`${origin}/auth/status`"), 'CAIt app bridge should read auth status before same-origin context handoff.');
assert.ok(caitAppBridge.includes("headers['x-aiagent2-csrf'] = csrfToken"), 'CAIt app bridge should attach CSRF token to same-origin context handoff writes.');
assert.ok(caitAppBridge.includes('createServerAppContextWithRetry'), 'CAIt app bridge should retry server-side app context writes.');
assert.ok(caitAppBridge.includes('fetchJsonWithTimeout'), 'CAIt app bridge should bound app context network waits.');
assert.ok(!analyticsJs.includes("source_app: 'publisher_approval_studio'"), 'Analytics Console JS should not contain Publisher app logic.');
assert.ok(!analyticsJs.includes("source_app: 'lead_ops_console'"), 'Analytics Console JS should not contain Lead Ops app logic.');
assert.ok(!analyticsJs.includes("source_app: 'delivery_manager'"), 'Analytics Console JS should not contain Delivery Manager app logic.');
assert.ok(publisherJs.includes("source_app: 'publisher_approval_studio'"), 'Publisher app logic should stay in publisher-approval.js.');
assert.ok(publisherJs.includes('/api/delivery-items?surface=publisher'), 'Publisher should load normalized publisher delivery items from the SaaS DB.');
assert.ok(!publisherJs.includes("source_app: 'analytics_console'"), 'Publisher JS should not contain Analytics app logic.');
assert.ok(!publisherJs.includes("source_app: 'lead_ops_console'"), 'Publisher JS should not contain Lead Ops app logic.');
assert.ok(!publisherJs.includes("source_app: 'delivery_manager'"), 'Publisher JS should not contain Delivery Manager app logic.');
assert.ok(leadOpsJs.includes("source_app: 'lead_ops_console'"), 'Lead Ops app logic should stay in lead-ops.js.');
assert.ok(leadOpsJs.includes('/api/delivery-items?surface=lead'), 'Lead Ops should load normalized lead/email delivery items from the SaaS DB.');
assert.ok(!leadOpsJs.includes("source_app: 'analytics_console'"), 'Lead Ops JS should not contain Analytics app logic.');
assert.ok(!leadOpsJs.includes("source_app: 'publisher_approval_studio'"), 'Lead Ops JS should not contain Publisher app logic.');
assert.ok(!leadOpsJs.includes("source_app: 'delivery_manager'"), 'Lead Ops JS should not contain Delivery Manager app logic.');
assert.ok(deliveryManagerJs.includes("source_app: 'delivery_manager'"), 'Deliveries feature logic should stay in delivery-manager.js.');
assert.ok(!deliveryManagerJs.includes("source_app: 'analytics_console'"), 'Delivery Manager JS should not contain Analytics app logic.');
assert.ok(!deliveryManagerJs.includes("source_app: 'publisher_approval_studio'"), 'Delivery Manager JS should not contain Publisher app logic.');
assert.ok(!deliveryManagerJs.includes("source_app: 'lead_ops_console'"), 'Delivery Manager JS should not contain Lead Ops app logic.');
assert.ok(html.includes('href="/agents.html"'));
assert.ok(html.includes('href="/publish-ai-agents.html"'));
assert.ok(html.includes('href="/ai-agent-api.html"'));
assert.ok(html.includes('href="/resources.html"'));
assert.ok(chatHtml.includes('href="/cli-help.html"'));
assert.ok(chatHtml.includes('href="/apps.html"'));
assert.ok(chatHtml.includes('href="/help.html"'));
assert.ok(chatHtml.includes('href="/news.html"'));
assert.ok(chatHtml.includes('id="openChatListBtn"'));
assert.ok(chatHtml.includes('id="openWorkerListBtn"'));
assert.ok(chatHtml.includes('id="openAppListBtn"'));
assert.ok(chatHtml.includes('id="openInfoBtn"'));
assert.ok(chatHtml.includes('id="activeLeaderStatus"'), 'Chat should show the current CAIt/leader conversation owner.');
assert.ok(chatHtml.includes('id="utilityModal"'));
assert.ok(appsHtml.includes('/apps.js?v=20260505b'), 'Apps page should load the server-side context history controller.');
assert.ok(appsHtml.includes('data-app-registry-list'), 'Apps page should expose the live app registry list.');
assert.ok(appsHtml.includes('/.well-known/mcp.json'), 'Apps page should expose MCP discovery metadata.');
assert.ok(appsHtml.includes('Recent app contexts'), 'Apps page should expose server-side app context history.');
assert.ok(appsHtml.includes("server-side context API"), 'Apps page should explain the server-side app context API.');
assert.ok(appsJs.includes('/api/apps?limit=100'), 'Apps JS should load registered apps from the app catalog API.');
assert.ok(appsJs.includes('MCP ready'), 'Apps JS should label MCP-ready app manifests.');
assert.ok(appsJs.includes('/api/app-contexts?limit=10'), 'Apps JS should load recent contexts from CAIt, not local browser storage.');
assert.ok(!appsJs.includes('localStorage'), 'Apps JS should not use localStorage for context history.');
assert.ok(!appsHtml.includes('localStorage'), 'Apps page copy should not describe localStorage-based context transfer.');
assert.ok(!/\b(?:localStorage|sessionStorage|indexedDB)\b|(?:^|[^\w])caches\./.test(appSurfaceSources), 'CAIt app surfaces should not use browser persistence APIs.');
assert.ok(!analyticsLoaderJs.includes('localStorage'), 'Analytics loader should not use browser localStorage for opt-out state.');
assert.ok(!clientJs.includes('localStorage'), 'Legacy client shell should not use browser localStorage for analytics opt-out state.');
assert.ok(analyticsLoaderJs.includes('cait_disable_ga4'), 'Analytics opt-out should use the shared cookie name.');
assert.ok(clientJs.includes('cait_disable_ga4'), 'Legacy client shell should use the shared analytics opt-out cookie name.');
assert.ok(!html.includes('/chatux/'), 'Root HTML must not reference /chatux.');
assert.ok(!chatHtml.includes('/chatux/'), 'Chat HTML must not reference /chatux.');
assert.ok(!html.includes('?tab=work'));
assert.ok(!html.includes('?tab=agents'));
assert.ok(!chatHtml.includes('?tab=work'));
assert.ok(!chatHtml.includes('?tab=agents'));
assert.ok(!html.includes('window.location.replace'), 'Root must render landing content directly instead of redirecting to /chatux.');
assert.ok(!html.includes('id="reviewPanel"'));
assert.ok(!html.includes('id="draftPanel"'));
assert.ok(!html.includes('Source-backed research first'));
assert.ok(!html.includes('Pass research into child agents'));
assert.ok(!html.includes('Show blockers before claiming execution'));
assert.ok(homeCss.includes('.home-hero'), 'Home CSS should style the landing hero.');
assert.ok(homeCss.includes('.builder-doc-section'), 'Home CSS should style the builder LP.');
assert.ok(appConsoleCss.includes('.app-console-shell'), 'App Console CSS should style the new CAIt app shell.');
assert.ok(appConsoleCss.includes('.side-nav'), 'App Console CSS should include old-GA-style side navigation.');
assert.ok(!appConsoleCss.includes('radial-gradient'), 'App Console CSS should avoid decorative gradient blobs.');

assert.ok(caitAppBridge.includes('cait-app-context/v1'), 'Shared app bridge should enforce the CAIt app context schema.');
assert.ok(caitAppBridge.includes('sendContextToCait'), 'Shared app bridge should expose Send to CAIt.');
assert.ok(caitAppBridge.includes('fetchCaitAppContextFromUrl'), 'Shared app bridge should let apps receive server-side CAIt contexts by id/token.');
assert.ok(caitAppBridge.includes('consumeCaitAppContextForChat'), 'Shared app bridge should let chat consume returned app context.');
assert.ok(caitAppBridge.includes('/api/app-contexts'), 'Shared app bridge should use the generic server-side app context API when possible.');
assert.ok(caitAppBridge.includes('BroadcastChannel'), 'Shared app bridge should notify an already-open chat without browser persistence.');
assert.ok(caitAppBridge.includes('app_context_id'), 'Shared app bridge should support server-side app context ids.');
assert.ok(caitAppBridge.includes('cait_app_context_id'), 'Shared app bridge should support CAIt app handoff context ids.');
assert.ok(!caitAppBridge.includes('localStorage'), 'Shared app bridge should not use browser localStorage for app context transfer.');
assert.ok(!caitAppBridge.includes('cait_context'), 'Shared app bridge should not embed app context payloads into URLs.');

assert.ok(analyticsJs.includes('source_app: \'analytics_console\''), 'Analytics Console should create analytics app context.');
assert.ok(analyticsJs.includes('search_queries'), 'Analytics Console should include search query artifacts.');
assert.ok(analyticsJs.includes('fetchCaitAppContextFromUrl'), 'Analytics Console should receive CAIt contexts through the server context API.');
assert.ok(analyticsJs.includes('applyInboundContext'), 'Analytics Console should map inbound context into the visible console state.');
assert.ok(analyticsJs.includes('/api/connectors/google/assets?include=gsc,ga4'), 'Analytics Console should fetch connected GA4 and Search Console assets.');
assert.ok(analyticsJs.includes('/api/connectors/google/analytics-report'), 'Analytics Console should fetch GA4 and Search Console reports after source selection.');
assert.ok(analyticsJs.includes('googleReportSources'), 'Analytics Console should track whether GA4 and Search Console loaded separately.');
assert.ok(analyticsJs.includes('googleReportSources: {'), 'Analytics Console context should carry loaded GA4/Search Console source flags.');
assert.ok(analyticsJs.includes('Report loaded with warnings'), 'Analytics Console should surface partial Google report failures.');
assert.ok(analyticsJs.includes('Google connected, no sources returned'), 'Analytics Console should separate connected-empty Google accounts from OAuth failures.');
assert.ok(analyticsJs.includes('googleApiErrors'), 'Analytics Console context should carry structured Google API failures for diagnosis.');
assert.ok(analyticsJs.includes('GA4 not loaded'), 'Analytics Console should not label missing GA4 data as loaded.');
assert.ok(analyticsJs.includes('function normalizeGa4Property'), 'Analytics Console should normalize manual GA4 property IDs.');
assert.ok(analyticsJs.includes('els.ga4PropertyInput?.value'), 'Analytics Console should read the manual GA4 property ID before loading reports.');
assert.ok(analyticsJs.includes('Requested ${requested.ga4_property}'), 'Analytics Console should show which GA4 property was sent when GA4 loading fails.');
assert.ok(analyticsJs.includes('channel_landing_pages'), 'Analytics Console should carry channel-by-landing-page drilldowns.');
assert.ok(analyticsJs.includes('channel_sources'), 'Analytics Console should carry referral/source-medium drilldowns.');
assert.ok(analyticsJs.includes('channel-drilldown-btn'), 'Analytics Console should make channel rows directly clickable.');
assert.ok(analyticsJs.includes('data-channel'), 'Analytics Console should attach channel drilldown state to each channel row.');
assert.ok(analyticsJs.includes('Referral sites'), 'Analytics Console should give Referral a site/source drilldown view.');
assert.ok(analyticsJs.includes('cait_analytics_sources'), 'Analytics Console should remember the last loaded Google sources.');
assert.ok(analyticsJs.includes('applyCachedGoogleSources()'), 'Analytics Console should restore the last loaded GA4/Search Console selection on startup.');
assert.ok(analyticsJs.includes('saveCachedGoogleSources({ ga4: Boolean(ga4), gsc: Boolean(gsc) })'), 'Analytics Console should save only successfully loaded Google source selections.');
assert.ok(analyticsJs.includes("url.searchParams.set('action', 'analytics_connect')"), 'Analytics Console Google connect should always use the narrow analytics connector action.');
assert.ok(analyticsJs.includes("url.searchParams.set('scope_group', kind === 'analytics' ? 'ga4,gsc' : kind)"), 'Analytics Console Google connect should pass the selected source scope group.');
assert.ok(analyticsJs.includes("kind === 'analytics' ? 'google.read_ga4,google.read_gsc'"), 'Analytics Console combined Google connect should pass both analytics capabilities.');
assert.ok(analyticsJs.includes("kind === 'gsc' ? 'google.read_gsc' : 'google.read_ga4'"), 'Analytics Console source-specific Google connect should pass one selected Google capability.');
assert.ok(!analyticsJs.includes('/auth/status'), 'Analytics Console connect buttons should not be blocked by a preflight request before OAuth redirect.');
assert.ok(analyticsJs.includes('updateGoogleConnectLinks'), 'Analytics Console should keep real OAuth links updated with the current app context return path.');
assert.ok(analyticsJs.includes('caitAuthOrigin'), 'Analytics Console should submit OAuth to the official CAIt auth origin even from preview origins.');
assert.ok(analyticsJs.includes('currentAnalyticsReturnPath()'), 'Analytics Console Google connect should preserve the current app-context URL.');
assert.ok(analyticsJs.includes('analyticsReturnSearch'), 'Analytics Console should keep the order app-context query available across Google OAuth redirects.');
assert.ok(analyticsJs.includes("url.searchParams.set('return_to', currentAnalyticsReturnPath())"), 'Analytics Console Google connect should return users to the active app context.');
assert.ok(analyticsJs.includes('Google connection failed'), 'Analytics Console should show the exact Google connector failure instead of a generic disconnected state.');
assert.ok(analyticsJs.includes('readAuthErrorFromUrl'), 'Analytics Console should show OAuth callback errors after returning to the app.');
assert.ok(analyticsHtml.includes('id="connectSearchConsoleBtn"'), 'Analytics Console should expose a Search Console connect button.');
assert.ok(analyticsJs.includes('googleSearchConsoleSite'), 'Analytics Console context should carry selected Search Console site.');
assert.ok(analyticsJs.includes('googleGa4Property'), 'Analytics Console context should carry selected GA4 property.');
assert.ok(analyticsJs.includes('googleReportLoaded'), 'Analytics Console context should indicate whether live Google report rows were loaded.');
assert.ok(analyticsJs.includes('country_mix'), 'Analytics Console should carry country performance rows for leaders.');
assert.ok(analyticsJs.includes('analyticsQueriesCount'), 'Analytics Console should update side navigation counts from runtime data.');
assert.ok(analyticsJs.includes('No server-side app context is loaded yet.'), 'Analytics Console should render an explicit empty state before server context is loaded.');
assert.ok(!/japan esim|best esim|tokyo esim|starter data/i.test(analyticsJs), 'Analytics Console should not ship built-in sample analytics rows.');
assert.ok(publisherJs.includes('source_app: \'publisher_approval_studio\''), 'Publisher Studio should create publisher approval context.');
assert.ok(publisherJs.includes('approval_requests'), 'Publisher Studio should include approval requests.');
assert.ok(publisherJs.includes('fetchCaitAppContextFromUrl'), 'Publisher Studio should receive CAIt contexts through the server context API.');
assert.ok(publisherJs.includes('applyInboundContext'), 'Publisher Studio should map inbound context into editable approval packets.');
assert.ok(publisherJs.includes('/api/github/repos'), 'Publisher Studio should load GitHub repositories from the server.');
assert.ok(publisherJs.includes('/api/deliveries/execute'), 'Publisher Studio should use the delivery execution API for PR handoff.');
assert.ok(publisherJs.includes('confirm_execute'), 'Publisher Studio should explicitly confirm approval-gated PR handoff execution.');
assert.ok(publisherJs.includes('article_publish'), 'Publisher Studio should mark publish handoffs separately from generic code handoffs.');
assert.ok(publisherJs.includes('renderCounts'), 'Publisher Studio should update side navigation counts from runtime packets.');
assert.ok(publisherJs.includes('No publisher packet is loaded yet'), 'Publisher Studio should render an explicit empty state before server context is loaded.');
assert.ok(!/Japan eSIM|7-day Japan|directory-ai-agent-listing|post-japan-esim/i.test(publisherJs), 'Publisher Studio should not ship built-in sample publisher packets.');
assert.ok(leadOpsJs.includes('source_app: \'lead_ops_console\''), 'Lead Ops should create lead app context.');
assert.ok(leadOpsJs.includes('email_draft'), 'Lead Ops should include email draft artifacts.');
assert.ok(leadOpsJs.includes('outreach_plan'), 'Lead Ops should include channel, schedule, and trigger outreach plans.');
assert.ok(leadOpsJs.includes('event_triggered_outreach'), 'Lead Ops should represent event-triggered outreach approval requests.');
assert.ok(leadOpsJs.includes('scheduled_outreach'), 'Lead Ops should represent scheduled outreach approval requests.');
assert.ok(leadOpsJs.includes('/api/deliveries/execute'), 'Lead Ops should use the shared delivery executor for Resend sends.');
assert.ok(leadOpsJs.includes('/api/deliveries/schedule'), 'Lead Ops should use the shared delivery scheduler for Resend sends.');
assert.ok(leadOpsJs.includes("action_kind: 'resend_send'"), 'Lead Ops should route email sends through CAIt Resend.');
assert.ok(leadOpsJs.includes('fetchCaitAppContextFromUrl'), 'Lead Ops should receive CAIt contexts through the server context API.');
assert.ok(leadOpsJs.includes('applyInboundContext'), 'Lead Ops should map inbound context into reviewable lead rows.');
assert.ok(leadOpsJs.includes('leadAllNavCount'), 'Lead Ops should update side navigation counts from runtime rows.');
assert.ok(leadOpsJs.includes('No lead rows loaded.'), 'Lead Ops should render an explicit empty state before server context is loaded.');
assert.ok(!/Travel Creator|Remote Japan|Airport Arrival|example\.com\/japan-travel/i.test(leadOpsJs), 'Lead Ops should not ship built-in sample lead rows.');
assert.ok(deliveryManagerJs.includes('source_app: \'delivery_manager\''), 'Deliveries should create reusable delivery context.');
assert.ok(deliveryManagerJs.includes('delivery_files'), 'Delivery Manager should include delivery files.');
assert.ok(deliveryManagerJs.includes('fetchCaitAppContextFromUrl'), 'Delivery Manager should receive CAIt contexts through the server context API.');
assert.ok(deliveryManagerJs.includes('applyInboundContext'), 'Delivery Manager should map inbound context into delivery packages.');
assert.ok(deliveryManagerJs.includes('groupedDeliveries'), 'Delivery Manager should group runs by work item.');
assert.ok(deliveryManagerJs.includes('isLeaderDelivery'), 'Delivery Manager should put leader runs first inside each work item.');
assert.ok(deliveryManagerJs.includes('delivery-work-group'), 'Delivery Manager should render work items as dropdown groups.');
assert.ok(!deliveryManagerJs.includes('local delivery samples'), 'Delivery Manager should not depend on local delivery sample payloads.');

assert.ok(chatJs.includes("from './chat-engine.js?v=20260509a'"), 'Chat JS should use root-relative shared chat engine import.');
assert.ok(chatJs.includes("from './delivery-action-contract.js?v=20260501a'"), 'Chat JS should use root-relative delivery action import.');
assert.ok(chatJs.includes("from './cait-app-bridge.js?v=20260508e'"), 'Chat JS should receive app contexts through the shared CAIt app bridge.');
assert.ok(chatJs.includes('hydrateAppContextFromUrl'), 'Chat should hydrate app context handoffs on explicit app return.');
assert.ok(chatJs.includes('await consumeCaitAppContextForChat()'), 'Chat should await server-side app context retrieval before filling the composer.');
assert.ok(chatJs.includes('refreshAppContexts'), 'Chat Apps panel should load reusable app contexts from the server.');
assert.ok(chatJs.includes('/api/app-contexts'), 'Chat should read app context history through the server API.');
assert.ok(chatJs.includes('BroadcastChannel'), 'Chat should receive app context handoffs from a separate same-origin app window.');
assert.ok(chatJs.includes('data-app-context-load'), 'Chat should let users load a server-side app context back into the composer.');
assert.ok(chatJs.includes('refreshRecentJobs'), 'Chat history should be derived from the server job API.');
assert.ok(!chatJs.includes('localStorage'), 'Chat should not persist order, app, or agent history in browser localStorage.');
assert.ok(chatJs.includes('analytics-console'), 'Chat app catalog should include Analytics Console.');
assert.ok(chatJs.includes('publisher-approval-studio'), 'Chat app catalog should include Publisher and Approval Studio.');
assert.ok(chatJs.includes('lead-ops-console'), 'Chat app catalog should include Lead Ops Console.');
assert.ok(chatJs.includes('CORE_FEATURE_APP_IDS'), 'Chat should filter core CAIt features out of app manifests.');
assert.ok(!chatJs.includes("id: 'delivery-manager'"), 'Chat app catalog should not include Deliveries as an app.');
assert.ok(chatJs.includes("const CHATUX_RETURN_PATH = '/chat'"), 'OAuth and delivery return path should use the canonical chat route, not /chatux or /chat.html.');
assert.ok(chatJs.includes('CHATUX_OAUTH_RETURN_STATE_KEY'), 'Chat should keep a short-lived OAuth return snapshot for in-progress order recovery.');
assert.ok(chatJs.includes("url.searchParams.set('return_to', currentChatReturnPath());"), 'OAuth links should carry the active chat return path with restore identifiers.');
assert.ok(chatJs.includes("url.searchParams.set('cait_restore_chat', '1')"), 'Chat OAuth return paths should request active chat restoration.');
assert.ok(chatJs.includes("url.searchParams.set('cait_chat_session_id', sessionId)"), 'Chat OAuth return paths should include the active chat session id.');
assert.ok(chatJs.includes("url.searchParams.set('cait_order_id', orderId)"), 'Chat OAuth return paths should include the active order id.');
assert.ok(chatJs.includes("url.searchParams.set('cait_oauth_popup', '1')"), 'Chat Google connector return paths should mark popup OAuth returns.');
assert.ok(chatJs.includes('data-chat-oauth-popup="google"'), 'Chat Google connector approval links should open OAuth outside the active chat tab.');
assert.ok(chatJs.includes('function openChatOAuthPopup'), 'Chat should keep the active thread open while Google OAuth runs in a separate window.');
assert.ok(chatJs.includes("type: 'cait-oauth-return'"), 'OAuth popup returns should notify the original chat window.');
assert.ok(chatJs.includes('handleOAuthPopupReturnMessage'), 'Original chat should refresh connector/order state after popup OAuth completes.');
assert.ok(chatJs.includes('restoreChatOAuthReturnStateFromUrl'), 'Chat should restore the active thread immediately after Google OAuth returns.');
assert.ok(chatJs.includes('restoreRequestedChatSessionFromHistory'), 'Chat should fall back to server chat memory when the OAuth snapshot is unavailable.');
assert.ok(chatJs.includes("saveChatOAuthReturnState('oauth_link_click')"), 'Chat should save the latest runtime state immediately before OAuth navigation.');
assert.ok(chatJs.includes('function xAuthHref'), 'X OAuth links should be built centrally.');
assert.ok(!chatJs.includes('href="/auth/x">Connect X'), 'Chat should not use bare X OAuth links.');
assert.ok(chatJs.includes('maybeRenderAuthorityNotice(job'), 'Chat should render approval or connector requests while an order is still running.');
assert.ok(chatJs.includes("['failed', 'timed_out'].includes(String(job.status || '').trim().toLowerCase())"), 'Chat should not show stale connector approval cards on failed or timed-out orders.');
assert.ok(chatJs.includes('googleAuthHrefForAuthority'), 'Chat approval cards should link directly to the required Google connector scope.');
assert.ok(chatJs.includes("Connect Search Console") && chatJs.includes("Connect GA4"), 'Chat approval cards should label GA4 and Search Console connector actions separately.');
assert.ok(!chatJs.includes('/chatux/'), 'Chat JS must not navigate users to /chatux.');
assert.ok(chatJs.includes('function showChatListPanel'), 'Chat should expose recent chat/order list modal.');
assert.ok(chatJs.includes('function showWorkerListPanel'), 'Chat should expose worker/agent list modal.');
assert.ok(chatJs.includes('function initialAgentMapHtml'), 'Chat should render an initial agent map after workflow order acceptance.');
assert.ok(chatJs.includes('workflowCurrentLocationLabel'), 'Chat progress should show the current workflow phase and active agent.');
assert.ok(chatJs.includes('internalLeaderActive'), 'Chat progress should surface internal leader checkpoint runs instead of appearing stuck on the previous specialist.');
assert.ok(chatJs.includes("checkpoint: 'Leader checkpoint'"), 'Chat progress should label leader checkpoints explicitly.');
assert.ok(chatJs.includes('includeInternalLeaderSequence: workflowChildIsInternalLeaderSequenceRun'), 'Chat progress maps should include internal checkpoint nodes when they are the active run.');
assert.ok(chatJs.includes('function workflowPhaseProgressMapHtml'), 'Chat should render a progress map when the workflow phase changes.');
assert.ok(chatJs.includes('data-progress-narrator-stream'), 'Chat progress should render a live text activity stream during running orders.');
assert.ok(chatJs.includes('function syncProgressNarratorAnimation'), 'Chat progress should animate narrator text independently of poll responses.');
assert.ok(chatJs.includes('function stopLiveProgressNarrator'), 'Chat progress should stop the narrator stream when live order status tracking stops.');
assert.ok(chatJs.includes('liveProgressStoppedOrderIds'), 'Chat progress should remember intentionally stopped orders so backfill does not restart polling loops.');
assert.ok(chatCss.includes('.message-meta') && chatCss.includes('text-transform: none'), 'Chat message labels should preserve CAIt casing instead of rendering CAIT.');
assert.ok(chatJs.includes('function threadIsNearBottom'), 'Chat should only auto-scroll progress updates when the reader is already near the latest message.');
assert.ok(chatJs.includes('includeAdaptivePending: true'), 'Agent maps should show adaptive planned later layers instead of hiding all future action work.');
assert.ok(chatJs.includes('function leaderTextHasCmoSignal'), 'Chat intake routing should identify signup/channel/growth requests as CMO work.');
assert.ok(chatJs.includes('function leaderTextHasSpecificCpoSignal'), 'Chat intake routing should not treat generic Product/service labels as CPO work.');
assert.ok(chatJs.includes('function leaderTextHasSpecificCtoSignal'), 'Chat intake routing should require specific CTO/build architecture wording before choosing CTO.');
assert.ok(chatJs.indexOf("if (leaderTextHasCmoSignal(text, intent)) return 'cmo_leader';") < chatJs.indexOf("if (leaderTextHasSpecificCpoSignal(text)) return 'cpo_leader';"), 'Chat intake routing should prefer CMO over CPO when growth and product wording both appear.');
assert.ok(chatJs.indexOf("if (leaderTextHasCmoSignal(text, intent)) return 'cmo_leader';") < chatJs.indexOf("if (leaderTextHasSpecificCtoSignal(text)) return 'cto_leader';"), 'Chat intake routing should prefer explicit CMO growth intent before CTO wording.');
assert.ok(chatJs.includes('activeLeaderLocked: false'), 'Chat should track when a leader has been confirmed and locked.');
assert.ok(chatJs.includes('function lockedLeaderOwnerForPrompt'), 'Chat should preserve a confirmed leader unless the user explicitly asks to change it.');
assert.ok(chatJs.includes('leaderFollowupSpecialistTaskForText'), 'Leader follow-up artifact requests should draft specialist orders instead of single leader orders.');
assert.ok(chatJs.includes('suppressLeaderLock'), 'Specialist follow-up drafts should not be rewritten back to the locked leader on SEND ORDER.');
assert.ok(chatJs.includes('function suggestLeaderChangeIfNeeded'), 'Chat should ask before changing away from a confirmed leader.');
assert.ok(chatJs.includes('data-chat-action="keep-leader"'), 'Chat should offer a keep-current-leader action when a different leader is suggested.');
assert.ok(chatJs.includes('data-chat-action="switch-leader"'), 'Chat should offer an explicit switch-leader action instead of automatically changing the leader.');
assert.ok(chatJs.includes('leaderChangeRequested'), 'Chat should mark explicit user leader-change requests separately from automatic reclassification.');
assert.ok(chatJs.includes("chat-engine.js?v=20260509a"), 'Chat should cache-bust the chat engine when retry payload fields change.');
assert.ok(chatJs.includes('function retryDraftFromJob'), 'Chat should prepare retries from the previous persisted order.');
assert.ok(chatJs.includes('function handleRetryCommand'), 'Chat should treat typed retry commands as explicit retry preparation instead of a new order.');
assert.ok(chatJs.includes('retryCommandText(compact)'), 'Chat should prevent typed retry commands from becoming running-order followups.');
assert.ok(chatJs.indexOf('await handleRetryCommand(prompt)') < chatJs.indexOf('activeOrderFollowupAllowedText(prompt)'), 'Typed retry should be handled before active-order followup routing.');
assert.ok(chatJs.includes('preservePrompt: true'), 'Retry drafts should preserve the previous order prompt instead of redrafting from the retry message.');
assert.ok(chatJs.includes('preservePlan: plannedTasks.length > 0'), 'Retry drafts should mark previous workflow plans for preservation.');
assert.ok(chatJs.includes('workflowPlannedTasks: plannedTasks'), 'Retry drafts should carry previous workflow planned tasks.');
assert.ok(chatEngine.includes('active_leader_locked'), 'Chat engine should send active leader lock state in prepare and job payloads.');
assert.ok(chatEngine.includes('fallbackLeaderLocked'), 'Chat engine should ignore unlocked active leader fallbacks when deriving the conversation owner.');
assert.ok(chatEngine.includes('workflow_planned_tasks'), 'Chat engine should send preserved workflow planned tasks when retrying a workflow order.');
assert.ok(worker.includes('function applyActiveLeaderLockToOrderBody'), 'Worker should enforce locked chat leader routing server-side.');
assert.ok(worker.includes('function workflowPlannedTasksFromOrderBody'), 'Worker should read preserved workflow plans from retry order payloads.');
assert.ok(worker.includes('preservePlannedTasks'), 'Worker should bypass workflow plan expansion when retrying with a preserved plan.');
assert.ok(chatJs.includes('function showAppListPanel'), 'Chat should expose app list modal.');
assert.ok(chatJs.includes('registeredApps: []'), 'Chat should keep registered marketplace apps in state.');
assert.ok(chatJs.includes('const CHATUX_CATALOG_PAGE_SIZE = 10'), 'Workers and apps should initially load only ten catalog rows.');
assert.ok(chatJs.includes("api(catalogApiPath('/api/apps', options)"), 'Chat app list should refresh registered apps from the paged app registry API.');
assert.ok(chatJs.includes("api(catalogApiPath('/api/agents', options)"), 'Chat worker list should refresh workers from the paged agent registry API.');
assert.ok(chatJs.includes('data-utility-load-more'), 'Worker and app panels should lazy-load additional rows on demand.');
assert.ok(chatJs.includes('function warmUtilityCatalogs'), 'Chat should prefetch the first catalog page after auth.');
assert.ok(!chatJs.includes("api('/api/snapshot', { method: 'GET' })"), 'Worker/app panels should not fetch the full snapshot just to list workers.');
assert.ok(chatJs.includes('function showInfoPanel'), 'Chat should expose account/info modal.');
assert.ok(chatJs.includes("adminNavLink: $('adminNavLink')"), 'Chat should wire the admin nav link.');
assert.ok(chatJs.includes('activeLeader: null'), 'Chat should track whether CAIt or a leader owns the current conversation.');
assert.ok(chatJs.includes('function setConversationOwnerFromPrepared'), 'Chat should switch the visible conversation owner from prepare-order responses.');
assert.ok(chatJs.includes('CAIt specialist router'), 'Chat drafts should make direct specialist routing explicit.');
assert.ok(chatJs.includes('function intakeInitialAnswerSuggestions'), 'Intake choices should extract usable answers from the initial chat prompt.');
assert.ok(chatJs.includes('function intakeSuggestionLooksLikeQuestion'), 'Intake initial choices should reject question text as a confirmed answer.');
assert.ok(chatJs.includes('intake.originalPrompt') && !/function intakeSourceText[\s\S]{0,220}intake\.questions/.test(chatJs), 'Intake initial choice extraction should not treat generated intake questions as already selected answers.');
assert.ok(chatJs.includes('function seedIntakeInitialChoices'), 'Initial prompt-derived intake answers should be added to the editable composer.');
assert.ok(chatJs.includes('From initial request'), 'Initial prompt-derived intake answers should be visibly marked as confirmed candidates.');
assert.ok(
  chatJs.includes("els.adminNavLink.hidden = !(auth.isPlatformAdmin || auth.admin)")
    || chatJs.includes("els.adminNavLink.hidden = !(auth?.isPlatformAdmin || auth?.admin)"),
  'Chat should reveal admin only for platform admins.'
);
assert.ok(chatJs.includes('href="/admin">Admin</a>'), 'Info panel should include an admin shortcut for platform admins.');
assert.ok(chatJs.includes('function signOut'), 'Chat should expose sign out.');
assert.ok(chatJs.includes("await api('/auth/logout'"), 'Chat sign out should call the logout API.');
assert.ok(chatJs.includes('data-chat-logout'), 'Chat should render logout controls.');
assert.ok(chatJs.includes("new URL('/login', window.location.origin)"), 'Chat should client-gate unauthenticated static asset access.');
assert.ok(chatJs.includes("loginUrl.searchParams.set('next', nextPath || CHATUX_RETURN_PATH)"), 'Chat login gate should preserve the current chat path and context query.');
assert.ok(chatJs.includes("timeoutMs: 15000"), 'Chat auth checks should allow production auth/status to finish before surfacing session-unavailable states.');
assert.ok(chatJs.includes('function csrfRequiredApiError'), 'Chat API helper should detect CSRF write failures.');
assert.ok(chatJs.includes('await refreshAuthForUnsafeWrite'), 'Chat API helper should refresh auth before/retry browser writes that need CSRF.');
assert.ok(chatJs.includes("headers.set('x-aiagent2-csrf', state.auth.csrfToken)"), 'Chat API helper should attach refreshed CSRF tokens to unsafe same-origin writes.');
assert.ok(chatJs.includes("await apiWithRetry('/api/work/prepare-order'"), 'Chat should retry transient prepare-order failures before surfacing an error.');
assert.ok(chatJs.includes('maxAttempts: 5'), 'Chat prepare-order retry should wait through short production 5xx/429 bursts.');
assert.ok(chatJs.includes('intake.taskType || intake.task_type'), 'Intake answers should preserve the originally selected leader task.');
assert.ok(chatJs.includes('taskType: task'), 'Worker list selections should pass the selected task type into prepare-order.');
assert.ok(chatJs.includes('data-utility-agent-id'), 'Worker Use buttons should carry the selected agent id, not only the task type.');
assert.ok(chatJs.includes('selectedAgentId: agentId'), 'Worker Use should pin the selected agent in the order draft.');
assert.ok(chatJs.includes('function chatText'), 'Chat user-facing status text should go through a language helper.');
assert.ok(chatJs.includes('I will prepare an order in chat using'), 'Worker Use status should have an English UI copy path.');
assert.ok(chatJs.includes('prepared_in_chat: true'), 'Approved chat orders should mark the intake/preparation gate as already completed.');
assert.ok(chatJs.includes("await api('/api/jobs'"));
assert.ok(chatJs.includes("await api('/api/connectors/x/status'"));
assert.ok(chatJs.includes("await api('/api/connectors/x/post'"));
assert.ok(chatJs.includes('confirm_post: true'));
assert.ok(chatJs.includes('approved_x_username'));
assert.ok(chatJs.includes('approved_text'));
assert.ok(chatJs.includes('Final action: X Client Ops'), 'X Client Ops delivery card should use English copy.');
assert.ok(chatJs.includes('CAIt has attached the X post draft and strategy context prepared during the workflow.'), 'X Client Ops explanation should be English.');
assert.ok(chatJs.includes('function renderAppHandoffTools'), 'Chat deliveries should expose generic app handoff cards.');
assert.ok(chatJs.includes("String(job.status || '').trim().toLowerCase() !== 'completed'"), 'Chat app handoffs should only render for completed deliveries.');
assert.ok(chatJs.includes('function appHandoffRelevanceScore'), 'Generic app handoff cards should score relevance against the current delivery before rendering.');
assert.ok(chatJs.includes('handoffRelevanceScore'), 'Generic app handoff candidates should carry a relevance score.');
assert.ok(!chatJs.includes("id === 'delivery-manager'"), 'Generic app handoffs should not score Deliveries as an app handoff candidate.');
assert.ok(chatJs.includes('Only apps matched to this delivery'), 'App handoff copy should explain that unrelated apps are filtered out.');
assert.ok(!chatJs.includes('return appManifestSources()\\n    .filter((entry) => {\\n      if (!entry?.id || (!entry.entryUrl && !entry.baseUrl && !entry.handoff?.createUrl)) return false;'), 'App handoff should not display the raw app catalog for every delivery.');
assert.ok(chatJs.includes('data-app-agent-handoff'), 'Generic app handoff cards should be actionable from delivery chat.');
assert.ok(chatJs.includes('cait-app-agent-transfer/v1'), 'Generic app handoffs should use the CAIt transfer payload contract.');
assert.ok(chatJs.includes('handoff?.createUrl'), 'Generic app handoffs should call manifest-declared handoff endpoints.');
assert.ok(chatJs.includes("`/api/apps/${encodeURIComponent(manifest.id || appId)}/handoff`"), 'Generic app handoffs should use the CAIt same-origin handoff proxy.');
assert.ok(chatJs.includes('const data = await api(createUrl'), 'Generic app handoff proxy calls should use the chat API helper so CSRF/auth headers are attached.');
assert.ok(chatJs.includes('appContextFromTransferPayload'), 'Generic app handoff fallback should convert transfer packets into server-side app contexts.');
assert.ok(chatJs.includes('createAppAgentContextOpenUrl'), 'Generic app handoff fallback should create a server-side context open URL.');
assert.ok(chatJs.includes('cait_app_context_id'), 'Generic app handoff fallback should pass only context identifiers in the app URL.');
assert.ok(chatJs.includes('/api/app-contexts'), 'Generic app handoff fallback should use the server-side app context API.');
assert.ok(!chatJs.includes('appAgentFallbackHandoffUrl'), 'Generic app handoffs should not keep the legacy URL payload fallback helper.');
assert.ok(!chatJs.includes('cait_transfer'), 'Generic app handoffs should not embed serialized transfer payloads in URLs.');
assert.ok(!chatJs.includes('data-app-agent-open-transfer'), 'Generic app handoff cards should not expose transfer-payload fallback links.');
assert.ok(!chatJs.includes('最終アクション: X Client Ops'), 'X Client Ops delivery card should not show Japanese heading copy.');
assert.ok(!chatJs.includes('過程で作成されたX投稿案'), 'X Client Ops delivery card should not show Japanese description copy.');
assert.ok(chatJs.includes('URL.createObjectURL'));
assert.ok(chatJs.includes('navigator.clipboard'));
assert.ok(chatJs.includes('state.trackedOrderIds:') || chatJs.includes('trackedOrderIds: new Set()'), 'Tracked orders should be in-memory only for the active chat session.');
assert.ok(chatJs.includes('renderRestoredSessionOrderContext'), 'Restored chat sessions should render related order status/results inside the chat.');
assert.ok(chatJs.includes('data-chat-order-retry'), 'Restored order cards should offer an explicit retry confirmation path.');
assert.ok(chatJs.includes('deliveryOrderActionsHtml'), 'Terminal delivery updates should keep status/retry actions visible after connector returns.');
assert.ok(chatJs.includes("return ['completed', 'failed', 'timed_out'].includes"), 'Blocked approval waits should stay progress states, not terminal deliveries.');
assert.ok(chatJs.includes('restored-order-progress'), 'Restored order cards should keep progress details visible.');
assert.ok(chatCss.includes('.restored-order-card'), 'Chat CSS should style restored order history cards.');
assert.ok(chatJs.includes('recentJobsApiPath'), 'Recent chat/order history should come from the server job API.');
assert.ok(chatJs.includes('CHATUX_PROGRESS_MAX_POLLS'), 'Chat polling should have an explicit long-running order limit.');
assert.ok(chatJs.includes('Live progress polling reached its limit'), 'Chat polling pause copy should explain the background history fallback.');
assert.ok(chatJs.includes("status: 'paused'"), 'Chat polling limit should freeze the progress narrator instead of animating forever.');
assert.ok(chatCss.includes('.progress-narrator.ok .progress-narrator-caret'), 'Chat CSS should stop the narrator caret animation when progress is done or paused.');
assert.ok(chatJs.includes('isNonOrderConversationIntentText'), 'Chat should keep pause/status/help messages out of order dispatch.');
assert.ok(chatJs.includes('const matchesTracked = state.trackedOrderIds.has(safeId)'), 'Chat backfill should only auto-deliver explicitly tracked orders or active recovery candidates.');
assert.ok(chatJs.includes('if (!matchesTracked && !matchesRecovery) continue;'), 'Chat backfill should not dump every historical chatux job into a new chat.');
assert.ok(chatJs.includes('_caitRecoveryStartedAt'), 'Chat recovery matching should ignore older same-session jobs from before the current send attempt.');
assert.ok(chatJs.includes('client_order_id'), 'Chat order create should include a client order id for idempotent recovery.');
assert.ok(chatJs.includes('orderCreateRequestBody(payload)'), 'Chat order create should strip local recovery markers before POSTing.');
assert.ok(chatJs.includes('Retrying the same idempotent order request once'), 'Chat recovery should safely retry the same idempotent create request once.');
assert.ok(clientJs.includes('client_order_id'), 'Open Chat order create should include a client order id for idempotent recovery.');
assert.ok(clientJs.includes('orderCreateRequestBody(payload)'), 'Open Chat order create should strip local recovery markers before POSTing.');
assert.ok(clientJs.includes('same idempotent order request once'), 'Open Chat recovery should safely retry the same idempotent create request once.');
assert.ok(chatJs.includes('visibleDeliveryFiles(candidates)'), 'Chat delivery should hide internal workflow markdown bundles from user-facing files.');
assert.ok(clientJs.includes('visibleDeliveryFiles(run.output?.files)'), 'Open Chat delivery should hide internal workflow markdown bundles from user-facing files.');
assert.ok(deliveryManagerJs.includes('visibleDeliveryFiles(output.files)'), 'Delivery Manager should hide internal workflow markdown bundles from user-facing files.');
assert.ok(chatJs.includes('includeHistoricalTracked'), 'Chat backfill should ignore historical tracked orders while a current order is attached.');
assert.ok(chatJs.includes('renderTerminalDeliveries: false'), 'Chat startup should not render historical terminal deliveries automatically.');
assert.ok(!chatJs.includes("String(job?.parentAgentId || '').trim() === 'chatux'"), 'Chat startup recovery should not match all historical chatux parent jobs.');

assert.ok(chatCss.includes('.chatux-panel'));
assert.ok(chatCss.includes('grid-template-columns: minmax(240px, 300px) minmax(0, 1440px)'), 'Chat panel should keep a wide desktop workspace beside the session sidebar.');
assert.ok(chatCss.includes('.chatux-header-tools'));
assert.ok(chatCss.includes('.chatux-nav'));
assert.ok(chatCss.includes('.tool-icon-btn'));
assert.ok(chatCss.includes('.leader-status-pill'), 'Chat CSS should style the active leader status pill.');
assert.ok(chatCss.includes('.utility-modal'));
assert.ok(chatCss.includes('.progress-narrator-stream'), 'Chat CSS should style the live progress text stream.');
assert.ok(chatCss.includes('.utility-dialog'));
assert.ok(chatCss.includes('.utility-row'));
assert.ok(chatCss.includes('.x-post-card'));
assert.ok(chatCss.includes('.app-handoff-card'));
assert.ok(chatCss.includes('.app-context-card'), 'Chat should style context returned by CAIt apps.');
assert.ok(chatCss.includes('.app-handoff-row'));
assert.ok(chatCss.includes('.usage-panel'));
assert.ok(chatCss.includes('.file-actions'));
assert.ok(!chatCss.includes('radial-gradient'));
assert.ok(adminCss.includes('.admin-shell'), 'Admin CSS should style the dashboard shell.');
assert.ok(adminCss.includes('.metric-grid'), 'Admin CSS should style member-count metrics.');
assert.ok(adminCss.includes('.admin-accounts-grid'), 'Admin CSS should style the accounts table.');
assert.ok(adminCss.includes('.admin-gate[hidden]'), 'Admin CSS should hide gate panels when the hidden attribute is set.');
assert.ok(adminCss.includes('.admin-order-group'), 'Admin CSS should support grouped order rows.');
assert.ok(!adminCss.includes('radial-gradient'));

assert.ok(adminJs.includes("await api('/api/admin/dashboard'"), 'Admin should use the dedicated lightweight dashboard payload.');
assert.ok(adminJs.includes('const auth = snapshot.auth || {}'), 'Admin should read auth from the dashboard payload.');
assert.ok(adminJs.includes('function groupedOrders'), 'Admin should group order runs by work order.');
assert.ok(adminJs.includes('auth.isPlatformAdmin'), 'Admin should require platform admin access.');
assert.ok(adminJs.includes('function downloadAccountsCsv'), 'Admin should support downloading member account data.');
assert.ok(adminJs.includes('adminRegistrationsMetric'), 'Admin JS should render registration metrics.');
assert.ok(adminJs.includes("const ADMIN_LOCALE = 'en-US'"), 'Admin should force English locale formatting.');
assert.ok(adminJs.includes('new Intl.DateTimeFormat(ADMIN_LOCALE'), 'Admin dates should not inherit the browser locale.');
assert.ok(adminJs.includes('new Intl.RelativeTimeFormat(ADMIN_LOCALE'), 'Admin relative dates should not inherit the browser locale.');

assert.ok(stylesCss.includes('Chat visual refresh'), 'Shared public pages should use the chat-style visual refresh overrides.');
assert.ok(stylesCss.includes('--bg: #f6f7f5'), 'Shared public pages should use the chat background palette.');
assert.ok(stylesCss.includes('font-family: Inter, ui-sans-serif'), 'Shared public pages should use the root chat typography stack.');
assert.ok(stylesCss.includes('.topbar.box'), 'Shared public pages should style the common header shell.');
assert.ok(stylesCss.includes('.topbar .logo-link::before'), 'Shared public pages should show the CAIt icon in the common header.');
assert.ok(stylesCss.includes('.topbar .doc-nav .mini-btn'), 'Shared public pages should style doc navigation like the chat header.');

assert.ok(chatEngine.includes('task_type: taskType'), 'Prepare-order payload should carry an explicit selected task type.');
assert.ok(chatEngine.includes('selected_agent_id: selectedAgentId'), 'Prepare-order payload should carry the selected worker id.');
assert.ok(chatEngine.includes('skip_intake:'), 'Prepared chat dispatch should not be blocked by a duplicate intake pass.');
assert.ok(chatEngine.includes("source: 'chat_send_order'"), 'Chat dispatch should confirm the user approved running the selected worker.');

assert.ok(server.includes("import worker from './worker.js'"), 'Local server should import the Worker as the single API implementation.');
assert.ok(server.includes('worker.fetch('), 'Local server should delegate HTTP handling to worker.fetch.');
assert.ok(server.includes('createStaticAssetsBinding'), 'Local server should provide a Cloudflare Assets-compatible binding.');
assert.ok(server.includes('assetPathCandidates'), 'Local assets should support extensionless Worker asset requests.');
assert.ok(server.includes('BOOTSTRAP_STATE_JSON'), 'Local server should keep E2E bootstrap support.');
assert.ok(server.includes('WORKFLOW_DISPATCH_QUEUE'), 'Local server should provide a local queue binding for Worker workflow dispatch.');
assert.ok(server.includes('handleLocalEvents'), 'Local server may keep only the SSE development bridge outside Worker routes.');
assert.ok(!server.includes('function handleChatPageRequest'), 'Local server should not duplicate chat route gating; Worker owns it.');
assert.ok(!server.includes('function handleAdminPageRequest'), 'Local server should not duplicate admin route handling; Worker owns it.');
assert.ok(!server.includes('async function handleCreateWorkflowJob'), 'Local server should not duplicate job creation flow; Worker owns it.');
assert.ok(!server.includes('async function handleGoogleAuthStart'), 'Local server should not duplicate auth flow; Worker owns it.');
assert.ok(!server.includes('async function handleXConnectorPost'), 'Local server should not duplicate connector write routes; Worker owns them.');
assert.ok(!server.includes('async function handleStripeWebhook'), 'Local server should not duplicate billing/webhook flow; Worker owns it.');
assert.ok(publicHeaders.includes("form-action 'self' https://aiagent-marketplace.net"), 'Static asset CSP headers should allow the Analytics Console OAuth form to submit to the official CAIt auth origin.');
assert.ok(!server.includes("'/chatux'"));
assert.ok(!server.includes('/chatux/index.html'));
assert.ok(!server.includes('/chatux/chatux.css'));
assert.ok(worker.includes("'/chat.css'"));
assert.ok(worker.includes('/api/chat-memory'), 'Worker should expose a lightweight chat memory endpoint.');
assert.ok(worker.includes('auth: await chatMemoryAuthStatus'), 'Worker chat memory endpoint should return lightweight auth for faster chat first paint.');
assert.ok(worker.includes('async function handleChatPageRequest'), 'Worker should gate chat HTML behind login.');
assert.ok(worker.includes('async function handleAdminPageRequest'), 'Worker should serve the admin shell.');
assert.ok(worker.includes('function legacyLegalNoticeRedirect') && worker.includes("url.pathname !== '/tokushoho'"), 'Worker should redirect the old tokushoho URL to the English legal notice URL before assets extension handling.');
assert.ok(worker.includes("return fetchStaticAssetPath(request, env, '/admin'"), 'Worker admin route should request the extensionless asset and let the API enforce admin data access.');
assert.ok(!worker.includes('return redirect(adminLoginRedirectPath(request, env)'), 'Worker admin route should not create a server-side login redirect loop.');
assert.ok(worker.includes("loginUrl.searchParams.set('source', 'gate_chat')"), 'Worker chat gate should send users to the login screen with a gate source.');
assert.ok(worker.includes('authBaseUrl: baseUrl(request, env)'), 'Worker auth status should expose the canonical auth base URL.');
assert.ok(worker.includes('GOOGLE_OAUTH_SCOPE_GROUPS'), 'Worker Google OAuth should use explicit scope groups.');
assert.ok(worker.includes('googleOAuthScopeGroupsFromUrl'), 'Worker Google OAuth should derive scopes from requested capabilities.');
assert.ok(worker.includes('googleScopedOAuthScope'), 'Worker Google connector links should build the smallest requested scope set.');
assert.ok(worker.includes('googleGrantedCapabilities'), 'Auth status should expose granted Google capabilities for OAuth prompt suppression.');
assert.ok(chatJs.includes('googleAuthorityMissingGroups'), 'Chat approval UI should request only Google scope groups that are still missing.');
assert.ok(worker.includes("googleAccessToken: persistentGoogleConnector ? '' : token.access_token"), 'Worker should keep Google access tokens out of browser session cookies when a persistent connector is available.');
assert.ok(worker.includes("githubOAuthScope(env, action = 'login', capabilities = [])"), 'Worker GitHub OAuth should only request repo scope when a repo capability is requested.');
assert.ok(/async function handleGoogleAuthStart[\s\S]{0,600}existingSession\?\.user && action === 'login'/.test(worker), 'Worker Google analytics connect should still start OAuth when an existing chat session needs connector scopes.');
assert.ok(worker.includes("['link', 'connect'].includes(action)"), 'Worker Google connector callback should link both link and connect OAuth actions.');
assert.ok(worker.includes("error?.code === 'connector_reauth_required' && sessionHasGoogleOauth(session)"), 'Worker Google connector reads should fall back to a fresh Google session token when a stored connector lacks a refresh token.');
assert.ok(worker.includes("returnUrl.searchParams.set('auth_error', safeCode)"), 'Worker Google OAuth failures should return to the app with an auth_error instead of dumping users at the home page.');
assert.ok(worker.includes("form-action 'self' https://aiagent-marketplace.net"), 'Worker CSP should allow the Analytics Console OAuth form to submit to the official CAIt auth origin.');
assert.ok(worker.includes("'/admin.html'"));
assert.ok(worker.includes("'/admin.css'"));
assert.ok(worker.includes("'/admin.js'"));
assert.ok(worker.includes("'/chat.js'"));
assert.ok(worker.includes("'/chat.html'"));
assert.ok(worker.includes("'/home.css'"));
assert.ok(worker.includes("'/apps.html'"));
assert.ok(worker.includes("'/analytics-console.html'"));
assert.ok(worker.includes("'/publisher-approval.html'"));
assert.ok(worker.includes("'/lead-ops.html'"));
assert.ok(worker.includes("'/delivery-manager.html'"));
assert.ok(worker.includes("'/cait-app-bridge.js'"));
assert.ok(worker.includes('async function agentsCatalogPayload'), 'Worker should serve paged agent catalog payloads without building the full snapshot.');
assert.ok(worker.includes('async function appsCatalogPayload'), 'Worker should serve paged app catalog payloads without building the full snapshot.');
assert.ok(worker.includes('return json(await agentsCatalogPayload(storage, request));'), 'Worker /api/agents should use the paged catalog endpoint.');
assert.ok(worker.includes('return json(await appsCatalogPayload(storage, request));'), 'Worker /api/apps should use the paged catalog endpoint.');
assert.ok(worker.includes('/.well-known/mcp.json'), 'Worker should expose MCP discovery metadata.');
assert.ok(worker.includes('async function handleMcpRequest'), 'Worker should expose a public MCP endpoint.');
assert.ok(worker.includes('async function handleAppHandoff'), 'Worker should proxy generic app handoff requests.');
assert.ok(worker.includes('/api\\/apps\\/[^/]+\\/handoff'), 'Worker should expose /api/apps/:id/handoff.');
assert.ok(worker.includes('async function handleCreateAppContext'), 'Worker should accept generic app context payloads.');
assert.ok(
  worker.includes('/api/app-contexts') || worker.includes('API_ROUTES.APP_CONTEXTS') || worker.includes("apiRouteMatches(url.pathname, request.method, 'APP_CONTEXTS'"),
  'Worker should expose /api/app-contexts.'
);
assert.ok(worker.includes('/api/connectors/google/analytics-report'), 'Worker should expose the Google analytics report endpoint.');
assert.ok(worker.includes('analyticsdata.googleapis.com/v1beta'), 'Worker should call the GA4 Data API for report rows.');
assert.ok(worker.includes('analyticsadmin.googleapis.com/v1beta/accountSummaries'), 'Worker should call the current GA4 Admin account summaries endpoint.');
assert.ok(!worker.includes('analyticsadmin.googleapis.com/v1alpha/accountSummaries'), 'Worker should not use the old GA4 Admin account summaries endpoint.');
assert.ok(worker.includes('googleApiRecoveryHint'), 'Worker should return actionable Google API failure hints for source loading.');
assert.ok(worker.includes('Promise.allSettled(['), 'Worker GA4 detail rows should not make the whole GA4 report fail when one breakdown fails.');
assert.ok(worker.includes('function normalizeGoogleGa4PropertyName'), 'Worker should accept numeric GA4 property IDs and normalize them.');
assert.ok(worker.includes("'sessionDefaultChannelGroup', 'sessionSourceMedium'"), 'Worker should fetch channel source/referral detail from GA4.');
assert.ok(worker.includes('Math.min(20, Number(options.limit || 12)'), 'Worker queued sweep should allow a larger per-minute dispatch batch.');
assert.ok(worker.includes('/searchAnalytics/query'), 'Worker should call the Search Console Search Analytics API.');
assert.ok(worker.includes("repo_path: String(body.repo_path || body.repoPath || draft.repoPath"), 'Worker should pass Publisher PR handoff paths into GitHub executor PR creation.');
assert.ok(worker.includes('async function mutateAccountByLogin'), 'OAuth callbacks should have an account-scoped storage mutation helper.');
assert.ok(worker.includes('await mutateAccountByLogin(storage, account.login'), 'OAuth connector persistence should avoid full-state D1 rewrites during login.');
assert.ok(mcp.includes('tools/list'), 'MCP helper should support tool discovery.');
assert.ok(mcp.includes('resources/read'), 'MCP helper should support resource reads.');
assert.ok(mcp.includes('resources/templates/list'), 'MCP helper should support resource template discovery.');
assert.ok(mcp.includes('prompts/get'), 'MCP helper should expose prompt templates.');
assert.ok(mcp.includes('structuredContent'), 'MCP tool calls should return structured content for capable clients.');
assert.ok(!server.includes("from './lib/http-policy.js'"), 'Local server should not duplicate HTTP policy imports; Worker owns policy enforcement.');
assert.ok(worker.includes("from './lib/http-policy.js'"), 'Worker should use shared HTTP policy helpers.');
assert.ok(httpPolicy.includes("pathname === '/mcp' && verb === 'POST'"), 'Shared HTTP policy should rate-limit MCP POST traffic explicitly.');
assert.ok(worker.includes('await mutateAccountByLogin(storage, login'), 'OAuth account persistence should avoid full-state D1 rewrites during login.');
assert.ok(!worker.includes("'/chatux'"));
assert.ok(!worker.includes('/chatux/index.html'));
assert.ok(worker.includes('xAuthSuccessRedirectPath'), 'X OAuth callback should preserve the requested return path.');

console.log('ui qa passed');
